### ISSUE TITLE
Not signed on a journey

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#1]
As a HSL Procurement planner I see that in OMM there has went off automatic disruption for line 39 direction 1 (from Kamppi) journey 10:30 today. When asked from operator, reason is that driver could not sign on VPC because he/she forgot driver card home. Operator tells that journey has been driven with vehicle 1234. I will then check transitlogvehicle 1234's positioning history from 10:30 onwards to see if vehicle really has driven the journey.

1. OMM -> procurement planner: notification in the GUI about an unserviced journey XYZ at time T
2. OMM -> procurement planner: reason for deviation (Operator input) is forgotten driver card, journey is really driven with vehicle 1234
3. Procurement planner -> transitlog: enter vehicle number and time values to right hand search bar (and journey data from left hand bar)
3.1 Alternative use: OMM -> transitlog: link in OMM notification takes to journey in transitlog, only need for step 4
4. transitlog-> procurement planner: show location traces (and planned and deviation data from left hand search)

ADDED: Need to draw selected (planned) route (that it should have been driven) to see clearly if it really drove correct route.

**Comment by samijuhani** [comment]
Added feature for this route, draw given route to map.

**Comment by samijuhani** [comment]
Needs HFP data from dead runs. So needs https://github.com/HSLdevcom/transitlog-ui/issues/54 (or lighter implementation) first.

**Comment by samijuhani** [comment]
@hellej has been working with getting deadruns to database. Let us know when it is working.

**Comment by danieldunderfelt** [comment]
Everything included in this ticket is implemented except for the drawing. Is it still necessary?

**Comment by samijuhani** [comment]
Let's see that in another issue if it comes relevant still.
