### ISSUE TITLE
BUG: Map zoom level not correct in url state

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#139]
Opening link does not give the user exact same zoom level that sender had.

![image](https://user-images.githubusercontent.com/39256978/50634700-3effc900-0f58-11e9-9c9c-2a4c91f726bf.png)

https://dev-transitlog.hsldev.com/journey/20190102/1207/1506/1?line.lineId=1506&date=2019-01-02&route.routeId=1506&route.direction=1&mapBounds=24.966580867767338%2C60.205880944862486%2C24.982888698577884%2C60.21027872218769&time=12%3A25%3A23&vehicle=0030%2F00043&stop=1230103

**Comment by samijuhani** [comment]
Left the copied and right pasted view in incognito.

**Comment by danieldunderfelt** [comment]
That is because it centers on the route (or stop if selected) after it loads. I thought it was a good thing so I didn't fix it, so this is working as intended.

**Comment by danieldunderfelt** [comment]
I will change the behavior so that it always respects the map position from the URL.
