### ISSUE TITLE
BUG: Planned arrival time not correct

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#140]
Arrival time not shown, there is departure instead. As in picture here should be 11:56 instead of 11:59.

![image](https://user-images.githubusercontent.com/39256978/50638890-023bce00-0f68-11e9-8dff-0eb437eaab51.png)

**Comment by danieldunderfelt** [comment]
This is what the data shows, it will be resolved when the JORE export is fixed and imported.

**Comment by samijuhani** [comment]
Works now.
