### ISSUE TITLE
Time input

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#142]
Make time input smoother to use:
User should be able to input f.ex. 

- just number 8 -> 8:00:00
- 805 -> 8:05:00
- 80505 -> 8:05:05
- make so that : mark is not needed to input

**Comment by danieldunderfelt** [comment]
Sounds good! I'll get it done.

**Comment by danieldunderfelt** [comment]
Implemented in PR #145.
