### ISSUE TITLE
Vehicle requirement

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#143]
https://dev-transitlog.hsldev.com/journey/20190104/0522/4421/2?line.lineId=4421&mapBounds=24.683532714843754%2C60.22216842544523%2C24.9444580078125%2C60.292427229444954&sidePanelVisible=true&stop=1334144&route.routeId=4421&route.direction=2&time=05%3A36%3A00&vehicle=0012%2F01816&date=2019-01-04&journeyDetailsOpen=true

Vehicle required is C, teli, that vehicle 1816 is.

Data shows A1, B, teli, HSL-pun

**Comment by danieldunderfelt** [comment]
This is placeholder data from when the JORE export was still lacking. I have just now implemented the feature on a basic level in PR #144, so it is coming!
