### ISSUE TITLE
Wrong colour on time difference

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#162]
![image](https://user-images.githubusercontent.com/39256978/51169284-2676a380-18b4-11e9-8ffa-88f632516baf.png)

**Comment by samijuhani** [comment]
Departure time should be red as left early, not arrival time witch is ok.

**Comment by danieldunderfelt** [comment]
I'm on it!

**Comment by danieldunderfelt** [comment]
Fixed in PR #160 .
