### ISSUE TITLE
What's up with around midnight journeys 

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#164]
Take look why there is missing data around midnight regurlary. Bug in vehicle system or us?

![image](https://user-images.githubusercontent.com/39256978/51379352-e0ba1500-1b17-11e9-8266-e5e2045ce3d3.png)

**Comment by danieldunderfelt** [comment]
Probably us. The journeys show up when looking at the route journeys ("lähdöt" tab). I'll investigate why they don't show up in the timetable list.

**Comment by danieldunderfelt** [comment]
Should be fixed in #178 .

**Comment by samijuhani** [comment]
Working ok
