### ISSUE TITLE
Add route direction to journey list

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#165]
Users asked if route direction 1/2 could be added to left hand journey list, maybe next to line number.

**Comment by danieldunderfelt** [comment]
Do you mean the timetable list?

**Comment by samijuhani** [comment]
Yeah 
![image](https://user-images.githubusercontent.com/39256978/51515525-b7053480-1e1c-11e9-94bd-ca3f3b3b787e.png)

**Comment by danieldunderfelt** [comment]
Implemented in #190 .
