### ISSUE TITLE
Time incorrect when coming to a journey from OMM

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#166]
Transitlog now shows current time when coming to a journey with link from OMM (example https://dev-transitlog.hsldev.com/journey/20190121/0630/2206/1).

Should show journey start time in this case.

**Comment by danieldunderfelt** [comment]
This should be an easy fix.

**Comment by danieldunderfelt** [comment]
I also noticed that the "Näytä raportilla" button in OMM that leads to Transitlog uses a faulty URL where the are no slashes between the data values. This is a separate issue though.

**Comment by samijuhani** [comment]
Also map is centered to defaul Helsinki view, should be centered to journey. Please more details about OMM problem? Can't see it affecting anything?

**Comment by danieldunderfelt** [comment]
@samijuhani There was a button in a submenu in OMM that lead to Transitlog, but the URL was not formatted properly.

**Comment by samijuhani** [comment]
What is the problem in OMM formatting?

**Comment by danieldunderfelt** [comment]
The "näytä raportilla" button leads to a URL like this: `https://dev-transitlog.hsldev.com/journey/7990505488616837`. It's missing all the slashes and the values don't seem to make sense anyway.

![deepinscreenshot_select-area_20190206082238](https://user-images.githubusercontent.com/3145668/52324923-d0e17280-29eb-11e9-9393-1c6766125279.png)

**Comment by samijuhani** [comment]
Yeah url has not been implemented to that button yet. In the next version it is. Only Viestit - Häiriöt there is the correct url.

**Comment by danieldunderfelt** [comment]
OK good to know!
