### ISSUE TITLE
Stop grouping is a bit too agressive

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#168]
Stops should be grouped only when they have identical coordinates. Here are grouped stops from both sides of the road. Should not.

![image](https://user-images.githubusercontent.com/39256978/51516340-cf2a8300-1e1f-11e9-99ae-4b09a4fe1697.png)

**Comment by danieldunderfelt** [comment]
I set the area which the stops are grouped within to 3 meters, which groups stops with identical coordinates as well as stops that have almost identical coordinates which would otherwise be barely visible under other markers even on the closest zoom level.

The PR is #180.
