### ISSUE TITLE
Plan "homepage"

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#170]
Plan what should be shown first when opening app. Thinking area journeys is not the best default.

**Comment by danieldunderfelt** [comment]
Maybe some simple usage instructions?

Example:

![deepinscreenshot_select-area_20190206130148](https://user-images.githubusercontent.com/3145668/52337117-6fcb9600-2a0f-11e9-9b5a-a6ae825e8506.png)

**Comment by samijuhani** [comment]
It is clear for sure. Let's ask opinions.

**Comment by samijuhani** [comment]
Finnish text for now, please update

Käyttöohjeet
Transitlog näyttää karttapohjaisessa ohjelmassa julkisen liikenteen ajetuista lähdöistä toteutunutta historia- ja reaaliaikaista tietoa sekä vertaa toteutumia suunniteltuihin lähtöihin.  
•	Nollataksesi hakuvalinnat paina vasemmasta yläkulmasta ”Palauta asetukset” –nappia
•	Päivittääksesi viimeisimmän datan ohjelmaan ja päivittääksesi kellonajan reaaliaikaan paina vasemmasta yläkulmasta ”Päivitä”-nappia.
•	Sivun ylähakupalkissa asetetaan hakukriteerit, mitä haetaan. Ensimmäisenä on päivämäärä ja kellonaika valinnat. Päivämäärä pitää aina olla valittuna, kun tutkitaan lähtöjä. Seuraavaksi yläpalkissa näkyy kolme hakukenttää, joiden kautta voi hakea lähtöjä. Ensimmäisenä on linjan ja reitin kautta, toisena hakukenttänä on kulkuneuvo ja kolmantena hakumahdollisuutena on pysäkkihaku. 
•	Kun alkuvalinnat on tehty, vasempaan ikkunan avautuu listaus valitun reittien lähdöistä tai lähtöketjun eli kyseisen kulkuneuvon lähdöt ko. päivältä tai aikataulu-listaus kaikista linjoista, jotka käyttävät valittua pysäkkiä.
•	Yhtenä hakumahdollisuutena on myös käyttää sivun oikeassa alakulmassa olevaa  -nappia, jolla rajataan haluttu alue kartalta. Valittuna olevalta ajalta kaikki lähdöt, jotka ovat kulkeneet ko. alueella tuolloin tulevat listaukseen vasemmalle. Aikaväliä voidaan rajata aluehaun minuuttirajauksella päivämäärä-ikkunassa.
•	Valitse etsimäsi lähtö listasta, jotta saat tarkemmat tiedot lähdöstä. Kun listasta valitaan haluama lähtö, avautuu palkin viereen uusi ikkuna, josta löytyy tarkemmat tiedot ko. lähdöstä. Lähdöstä on kerrottu pysäkkikohtaisesti suunniteltu ja toteutunut lähtöaika sekä niiden erotus, joka on korostettu värein. Värit kertovat miten lähtö on ajettu suunnitellun ajoaikojen mukaisesti. Vihreä on ajallaan (0- +3 min), punainen on etuajassa ja keltainen on myöhässä (yli 3 min). Myös saapumisen kellonaika on kerrottu pysäkkikohtaisesti. 
•	Kartalla pysäkit ja reittiviiva on myös korostettu värein miten lähtö on ajanut suunniteltuun nähden. Väliaikapysäkit    on lisäksi korostettu sisältä keltaisella/punaisella, jos väliaikapysäkin lähtöaikaa ei ole noudatettu. Pysäkin merkkiväri on katkoviivainen  , jos pysäkillä ovet eivät ole avautuneet. Lisäksi bussin viereen tulee sininen pieni ympyrä, kun ovet ovat avoinna.  
•	Lähtö-/lähtöketju-/aikataululistaus-ikkunan saa piiloon vieressä olevasta  -kuvakkeesta. Infoikkunan saa myös piilotettua ikkunan oikealta reunalta  -kuvakkeesta.
•	Ylähakupalkin alareunassa on liukusäädin, jota liikuttamalla voidaan muuttaa aikaa. Kun tietty lähtö on valittuna, liukusäätimellä voi tarkastella juuri ko. lähdön tapahtumia. Live-painike vasemmalla yläkulmasta toistaa valitsemasi lähdön tapahtumat kartalle haluamallasi nopeudellasi. Nopeutta voi muokata päivämäärä-ikkunassa aikamuutos kohdassa.
