### ISSUE TITLE
Time setting buttons are hard to press with track pad

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#171]
There up/down arrows could be bigger. Hard to press with track pad multiple times.

![image](https://user-images.githubusercontent.com/39256978/51518325-2b90a100-1e26-11e9-94de-ee2c245c2461.png)

**Comment by danieldunderfelt** [comment]
Those aren't really supposed to be there. The browser puts them in for number inputs and I don't think I can control their style to any large extent. I can remove them though.

**Comment by danieldunderfelt** [comment]
These are now removed in PR #186 .
