### ISSUE TITLE
I see double

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#172]
Many journeys doubled on timetables list
https://dev-transitlog.hsldev.com/?line.lineId=2551&vehicle=&live=false&date=2019-01-22&mapView=60.18484875595129%2C24.919395446777347%2C13&time=13%3A17%3A00&stop=1173104&tab=timetables&route.routeId=2551&route.direction=2 
![image](https://user-images.githubusercontent.com/39256978/51532208-39571e00-1e48-11e9-9cfc-3801eab29247.png)

**Comment by danieldunderfelt** [comment]
Damn... there might be a bug with the import, working on it now.

**Comment by danieldunderfelt** [comment]
![deepinscreenshot_select-area_20190123145950](https://user-images.githubusercontent.com/3145668/51608402-06805900-1f20-11e9-9b77-4c7f1901f115.png)
This is not a bug, there are actually multiple identical-but-different departures in effect during the same time but with different start/end times. We should filter these out in the UI and only show the latest one.

**Comment by samijuhani** [comment]
No doubles seen anymore
