### ISSUE TITLE
30 hour problem

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#175]
https://dev-transitlog.hsldev.com/journey/20190122/0206/2235N/1?line.lineId=2235&vehicle=22%2F1021&mapView=60.21900856188765%2C24.813373088836673%2C16&live=false&date=2019-01-22&time=02%3A28%3A14&stop=2111209&tab=journeys&route.routeId=2235N&route.direction=1 vehicle icon not showing for journeys after 24rs.

**Comment by samijuhani** [comment]
Still there with 23:59-00:00 transition. User reported this, he also used Live mode that acts very funny. https://dev-transitlog.hsldev.com/journey/20190314/234600/1061N/1/0?mapView=60.21031603413946%2C24.948234558105472%2C12&line.lineId=1061&route.routeId=1061N&route.direction=1&date=2019-03-14&vehicle=18%2F658&live=true&time=61%3A23%3A30&time_increment=10

**Comment by danieldunderfelt** [comment]
The transition seems to work, but the simulation is broken. Fixed in #254.
