### ISSUE TITLE
Wrong colour in timing stop icon when left early

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#176]
Should be red.

![image](https://user-images.githubusercontent.com/39256978/51593473-e8543200-1efa-11e9-9057-b16b5dcf5207.png)

**Comment by danieldunderfelt** [comment]
Would be good to have a link to the journey where this happens. We also don't have the same HFP data anymore as we did when you found this bug, so could you look for a new case?

**Comment by danieldunderfelt** [comment]
The data has changed, so I'm closing this now. Feel free to open a new issue if the problem persists.
