### ISSUE TITLE
Live mode broken

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#191]
See https://drive.google.com/file/d/1HWoxjRAKhfnM2tbWsTlP2WTF1DthA-fS/view

**Comment by danieldunderfelt** [comment]
I'm on it!

**Comment by danieldunderfelt** [comment]
Fixed in #192.

**Comment by jamad** [comment]
If it was the fix for the missing icons for the vehicle on HSL map, thanks a lot. I have suffered from it since the end of January but did not know where to report the bug.

**Comment by samijuhani** [comment]
@jamad different project. Please report @ HSL Developer Community in Facebook or Twitter.

**Comment by jamad** [comment]
Thanks , @samijuhani. There are so many project on https://dev.hsl.fi/ so did not know which one. But will report it via Twitter next time.
