### ISSUE TITLE
Doubled journey

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#201]
https://dev-transitlog.hsldev.com/journey/20190213/072800/4573/1?vehicle=12%2F724&mapView=60.294086068431916%2C24.932441711425785%2C13&stop=1113435&route.routeId=4573&route.direction=1&line.lineId=4573&time=07%3A28%3A00&live=false&date=2019-02-13 this journey is driven with two separate busses. Make it so that journeys are separated.

**Comment by danieldunderfelt** [comment]
This will take some doing, as we haven't given a thought about journeys like these yet. We could probably separate them per vehicle ID...

**Comment by samijuhani** [comment]
Planned journey should have data what is the doubled and what original but hfp does not so separating by vehicle id might be the easiest.
