### ISSUE TITLE
Block view should have planned and actual arrival times also

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#204]
Users want to see also planned and actual arrival time to first stop in block view. Maybe with tab/toggle to show those and hide by default? Or smaller font always there?

**Comment by danieldunderfelt** [comment]
What is "block view"? The planned/actual arrival time should be visible in the journey details sidebar as well as the stop popup where doors were opened.

**Comment by samijuhani** [comment]
Lähtöketju

**Comment by samijuhani** [comment]
Decided not to implement at this point as users can see this easily with one click of a journey. Let's rethink later if necessary.
