### ISSUE TITLE
Terminal and recovery times are not clear

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#205]
User feedback: 

Termnal and recovery times are not easily understood as colours are red even one is minus and one plus times.  Suggested that planned time of terminal time and actual would also be shown with differential

![image](https://user-images.githubusercontent.com/39256978/52707940-9189c780-2f91-11e9-9b7d-db5b5bb121de.png)

**Comment by danieldunderfelt** [comment]
Good catch, the correct number is in the stop list. The logic is that the number is negative if the observed event happened before the planned time, and positive if it happened after. I changed the direction of the diff at some point to make it clearer in the code, but I must have forgotten to change the sign logic in the sidebar.
