### ISSUE TITLE
Update did not really update

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#207]
1. looking at the stop data in the morning
2. leave tab open to background, do everything else, including switching between wifi/lan
3. come back to using app, pressing update to get fresh data, nothing happens
4. F5 fixes

https://dev-transitlog.hsldev.com/?vehicle=&mapView=60.186851767280764%2C24.96119499206543%2C17&stop=1113131

**Comment by samijuhani** [comment]
Looks like update only updates jore data at the moment.

**Comment by danieldunderfelt** [comment]
That's exactly what it doesn't do. Update only ever updates HFP data, as there will never be new JORE data unless we import a new dataset. I'll have a look at why it's not updating for you.

**Comment by samijuhani** [comment]
Yeah. Scrolling the list updates data but not clicking update.

**Comment by samijuhani** [comment]
And those steps do not matter in this case so forget that.

**Comment by danieldunderfelt** [comment]
Fixed in #211.
