### ISSUE TITLE
Highlight stop in map when clicking/hovering over it in journey details bar 

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#208]
Also make stop name clickable as stop time is at the moment. User did not find this clicking feature as only tried to click stop name.

![image](https://user-images.githubusercontent.com/39256978/52783106-84381000-3059-11e9-9df4-d891542a8db4.png)

**Comment by danieldunderfelt** [comment]
Heheh, I saw the need for this myself and already implemented it in #200. It will allow you to skip forward in the journey to the stop by clicking the stop, and it selects the stop too, which results in the stop popup and timetable list opening.

**Comment by samijuhani** [comment]
Clicking stop name should maybe center the map to that stop? Now clicked stop may be in the corner of map.

**Comment by danieldunderfelt** [comment]
It should do that, yes. It looks like it tries to do it, but is not allowed to finish the pan animation. I'll have a look at some point.

**Comment by samijuhani** [comment]
Also take a look if the hovering part is also possible? So hoverin stop in info list could highlight the stop in map?

**Comment by danieldunderfelt** [comment]
Ok, I'll have a look.

**Comment by danieldunderfelt** [comment]
Hover implemented in #220.
