### ISSUE TITLE
What are these in area search list

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#215]
Those times starting 35:00:00 

https://dev-transitlog.hsldev.com/journey/20190218/351800/4611/2/0?vehicle=30%2F16&mapView=60.233249519326534%2C24.993553161621097%2C12&areaBounds=24.955894947052006%2C60.18538219301049%2C24.963598251342777%2C60.18824126792973&route.routeId=4611&route.direction=2&line.lineId=4611 

![image](https://user-images.githubusercontent.com/39256978/52943657-49deb380-3376-11e9-93d6-774068d84a75.png)

**Comment by danieldunderfelt** [comment]
Good catch, I'll investigate! It would be best if the 30h day info would be present in the HFP data, this looks like a side-effect of my guessing.
