### ISSUE TITLE
Minor: Departure time calculated before departure incorrectly

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#219]
Departure time is told before actual departure when journey has not departured yet. Departure time updates fine after departure but before that there is incorrect data. Should be empty.

![image](https://user-images.githubusercontent.com/39256978/52952270-bb296100-338c-11e9-904b-d7bcf843b805.png)

**Comment by samijuhani** [comment]
Actual departure time

https://dev-transitlog.hsldev.com/?vehicle=&mapView=60.260950503475456%2C24.85587537288666%2C18&stop=4150263&live=false&date=2019-02-18&time=14%3A53%3A06 
 
![image](https://user-images.githubusercontent.com/39256978/52952358-f62b9480-338c-11e9-9325-0f84f2103026.png)

**Comment by danieldunderfelt** [comment]
We don't know when it actually departures before the next_stop_id data changes. Should we just ignore all journeys that only have events from one stop?

**Comment by samijuhani** [comment]
Maybe that would be it if it is easy to do. Data is false now if you look at it just before departure.

**Comment by danieldunderfelt** [comment]
Yeah, we can do that!

**Comment by danieldunderfelt** [comment]
What do you mean by "data is false"? No events with next_stop_id = false can show up in the timetable list since the observed times are fetched by the stop ID.

I'll look into ignoring events from journeys that haven't visited more than one stop.

**Comment by danieldunderfelt** [comment]
I don't think it is feasible to do this now. Lets wait for HFP 2 and query for the current stop where it can be false before the departure happens.

Currently, the last event with the next_stop_id of [current stop] is when the departure happens for all intents and purposes. If the journey is ongoing and the vehicle hasn't departed yet, that's all the data we have.

**Comment by samijuhani** [comment]
Ok
