### ISSUE TITLE
Wrong route line 20,2121B

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#226]
Planned route should be like driven from 5.2.

**Comment by danieldunderfelt** [comment]
Do you have a link to this view?

**Comment by danieldunderfelt** [comment]
This looks like the same issue that's fixed in #224. Let's wait for that PR to land and then we can test again.

**Comment by samijuhani** [comment]
https://dev-transitlog.hsldev.com/journey/20190221/071100/1021/2/0?vehicle=17%2F55&live=false&date=2019-02-21&time=07%3A11%3A00&mapView=60.15707672826544%2C24.908151626586914%2C14&line.lineId=1021&route.routeId=1021&route.direction=2

**Comment by samijuhani** [comment]
![image](https://user-images.githubusercontent.com/39256978/53148552-b4306780-35b3-11e9-88b2-8fd6088492d9.png)

**Comment by samijuhani** [comment]
Route was modified 4.2., shown in Transitlog is that older one still. From 5.2. should go as driven.

**Comment by danieldunderfelt** [comment]
I'll check if the route filter branch fixes the issue.

**Comment by danieldunderfelt** [comment]
Direction one shows the new route in the `filter-jore-data` branch, but direction 2 still shows the old one. I'll make sure that the correct geometry is fetched, and can you ensure that the route is updated correctly in JORE for both directions?

**Comment by samijuhani** [comment]
D2 
![image](https://user-images.githubusercontent.com/39256978/53149547-aaf4ca00-35b6-11e9-93b8-024823f92d77.png)

**Comment by samijuhani** [comment]
Direction 1 is correct already.

**Comment by danieldunderfelt** [comment]
Thanks! There is definitely a bug in the UI where the wrong dateBegin/dateEnd parameters are given to the geometry query. I'll fix it and include the fix in #224.

**Comment by samijuhani** [comment]
Good!

**Comment by danieldunderfelt** [comment]
This is now fixed.
