### ISSUE TITLE
Highlight special days in calendar

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#229]
Special day = week holiday etc where f.ex. in monday, sunday traffic is driven. Get this from Jore.

**Comment by samijuhani** [comment]
Hovering mouse over special day gives tooltip/pop up saying what special day it is.

**Comment by danieldunderfelt** [comment]
We need additional tables included in the JORE export, so lets put this feature on ice until we have those. I tried checking a list of holidays, but there were many that make no difference for our purposes, so I'd prefer to wait for the JORE data and then look up what holiday each special day is from the list. The list can be downloaded here in JSON format: http://www.webcal.fi/fi-FI/muut_tiedostomuodot.php

**Comment by samijuhani** [comment]
2P
Su
Ma

Is the order
