### ISSUE TITLE
Add native pop up if user uses IE

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#233]
"IE is not supported, please use Chrome or Firefox" pop up if user opens app with IE or other surely-not-supported browser. Use browsers native notification.

**Comment by samijuhani** [comment]
Not getting pop up, only black screen. IE11

**Comment by danieldunderfelt** [comment]
Hmm okay, makes sense. It's not even a bit compatible... I don't have IE on hand to test with, but I'll try showing the popup before loading the rest of the scripts.

**Comment by danieldunderfelt** [comment]
Fixed in #248, but should still be tested with IE.
