### ISSUE TITLE
Live option not working with area search.

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#238]

**Comment by samijuhani** [comment]
Trying to reproduce the case as it works now.

**Comment by samijuhani** [comment]
Closing for now, cannot reproduce.

**Comment by samijuhani** [comment]
And reproduced

**Comment by samijuhani** [comment]
https://drive.google.com/file/d/1xT0AWvy-A4g7_tz6lxXh_yf-quExBU1M/view

**Comment by danieldunderfelt** [comment]
Fixed in #242.
