### ISSUE TITLE
Deprecation info in Chrome console

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#241]
content-script.js:59 [Deprecation] HTML Imports is deprecated and will be removed in M73, around March 2019. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 for more details.
a.(anonymous function) @ content-script.js:59
content-script.js:54 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.

**Comment by danieldunderfelt** [comment]
This probably comes from one of your browser plugins. Either way, the best we can do is update the app's dependencies when deprecation warnings appear. I would also catch them in development before the code appears on the server if the warning concerned our code.
