### ISSUE TITLE
788 missing Porvoo stop events

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#250]
This missing stop events even though there is data for the whole trip. Stop events missing from Porvoo stops.

 https://dev-transitlog.hsldev.com/journey/20190312/061000/9788/1/0?vehicle=18%2F251&mapView=60.38802901834137%2C25.546882152557377%2C16&line.lineId=9788&route.routeId=9788&route.direction=1&live=false&time=07%3A25%3A48

![image](https://user-images.githubusercontent.com/39256978/54197033-8f9d2080-44cb-11e9-9b01-0ee896e03568.png)

**Comment by samijuhani** [comment]
Also 788 direction 2 data is completely missing. Must be same thing.

**Comment by danieldunderfelt** [comment]
As stated in the previous issue about 778 (#243), the next_stop_id information is missing from the data, which makes it impossible to match the events to stops:

![DeepinScreenshot_select-area_20190312134306](https://user-images.githubusercontent.com/3145668/54197537-e0614900-44cc-11e9-83d2-4b5aed5c0efb.png)

**Comment by samijuhani** [comment]
Oh. Reporting bug to Tieto
