### ISSUE TITLE
616 route problem

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#251]
This https://dev-transitlog.hsldev.com/journey/20190311/162800/4616/1/0?vehicle=12%2F1539&mapView=60.18506294155638%2C24.954706194112077%2C14&date=2019-03-11&line.lineId=4616&route.routeId=4616&route.direction=1&live=false&time=16%3A28%3A00

![image](https://user-images.githubusercontent.com/39256978/54264313-79e73400-457b-11e9-8aca-24ea3cb455e4.png)

Should be this from 4.3.2019

![image](https://user-images.githubusercontent.com/39256978/54264349-88cde680-457b-11e9-88e5-f139982bd524.png)

**Comment by danieldunderfelt** [comment]
This is the same issue as the other issue about the same thing, there are simply many valid stops and the app can't distinguish between them. It's good to have more cases to test with and I'll try to fix it by adding the modified date to JORE.

**Comment by samijuhani** [comment]
Working ok now.
