### ISSUE TITLE
Zoom defaults incorrectly when choosing route

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#253]
Zooms to these coordinates always when choosing any route. https://dev-transitlog.hsldev.com/?vehicle=&mapView=60.18685%2C24.9612%2C13&stop=1113131&live=false&date=2019-03-14&time=09%3A52%3A58&route.routeId=2227V&route.direction=1&line.lineId=2227

**Comment by danieldunderfelt** [comment]
Yeah, I noticed. I have to update jore-history first and then I can fix this.
