### ISSUE TITLE
Incorrect arrival time for the first stop

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#259]
https://dev-transitlog.hsldev.com/journey/20190319/092000/1092/1/0?vehicle=22%2F880&mapView=60.210074838273%2C25.076712369918823%2C18&line.lineId=1092&route.routeId=1092&route.direction=1&live=false&time=09%3A15%3A15&time_increment=5&tab=vehicle-journeys 

![image](https://user-images.githubusercontent.com/39256978/54592067-42bdca80-4a34-11e9-85a2-e4c007d96c3a.png)

**Comment by danieldunderfelt** [comment]
The events have been cleared already, but this probably related to the fact that arrival is calculated by door openings. HFP 2 will bring improvement to this.

**Comment by danieldunderfelt** [comment]
This is probably fixed now that events are in use.

**Comment by danieldunderfelt** [comment]
@samijuhani this can probably be closed.
