### ISSUE TITLE
Bad data from vehicle, does not open journey details tab

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#264]
https://dev-transitlog.hsldev.com/journey/20190328/135800/2549/2?mapView=60.198075437545796%2C24.74481582641602%2C13&vehicle=0022%2F1021&route.routeId=2549&route.direction=2&live=false&line=2125&time=13%3A58%3A00&tab=vehicle-journeys

**Comment by samijuhani** [comment]
Loads forever, details tab does not open. Vehicle is somehow faulty, that is known. We should be robust for that though.

**Comment by danieldunderfelt** [comment]
Yes, agreed. I'll have a look!

**Comment by danieldunderfelt** [comment]
It does seem to load well today, even the journeys that are not in the cache are pretty snappy. Is it still happening for you?

**Comment by samijuhani** [comment]
Got few to load nicely at first but after clicking through vehicles journeys, stops loading any

**Comment by samijuhani** [comment]
https://dev-transitlog.hsldev.com/journey/20190328/131800/2549/1?mapView=60.1982034116533%2C24.744987487792972%2C12&vehicle=0022%2F1021&route.routeId=2549&route.direction=1&live=false&line=2549&time=13%3A18%3A00&tab=vehicle-journeys&date=2019-03-28 f.ex. this does not load now.

**Comment by danieldunderfelt** [comment]
I found the bug on the server and this is now fixed.
