### ISSUE TITLE
UI goes out of the screen with surface laptop

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#266]
![image](https://user-images.githubusercontent.com/39256978/55223627-4c56e780-5217-11e9-9e92-61e8b01adbed.png)

**Comment by samijuhani** [comment]
Right side of the screen is not visible with my surface pro even though browser is fitted to full screen

**Comment by danieldunderfelt** [comment]
What should be the minimum resolution for the app? I increased it a bit to fit the graph but I'll set it to 1366px since that's a common width.

**Comment by danieldunderfelt** [comment]
This should not be an issue anymore.

**Comment by danieldunderfelt** [comment]
@samijuhani this can probably be closed.
