### ISSUE TITLE
Unexpected auto-hide of journey detail view

### ISSUE THREAD

**Issue by th0rgall** [HSLdevcom/transitlog-ui#274]
Video illustrating the problem [here](https://www.youtube.com/watch?v=AmYQQxxKacY&feature=youtu.be).

If the stop detail view is not enabled, clicking another stop in the journey table will show a loading detail view that will auto-hide itself. This auto-hiding is unexpected. It should show the detail without hiding it.

**Comment by danieldunderfelt** [comment]
Thanks for reporting! This should be fixed with the PR #282.
