### ISSUE TITLE
"Filter by vehicle" translation not changing at language change

### ISSUE THREAD

**Issue by th0rgall** [HSLdevcom/transitlog-ui#277]
Problem illustration video [here](https://youtu.be/lCRZTUvS2PA).

The text label key seems to be right. Maybe the VehicleSettings component is not re-rendered properly ([here](https://github.com/HSLdevcom/transitlog-ui/blob/master/src/components/filterbar/VehicleSettings.js#L23)) on a language change.

**Comment by danieldunderfelt** [comment]
Good catch! Fix coming in PR #282.
