### ISSUE TITLE
Clicking journey from area search crashes app

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#279]
Choose a journey from area serach list -> crash

**Comment by danieldunderfelt** [comment]
I'm on it!

**Comment by samijuhani** [comment]
Now it does not crash but journeys are not selected when clicked. https://dev-transitlog.hsldev.com/?vehicle=&mapView=60.1515130972661%2C24.9145781993866%2C16&line=1007&route.routeId=1007&route.direction=2&live=false&time=14%3A11%3A00&areaBounds=24.91147756576538%2C60.149964510392195%2C24.9260687828064%2C60.15569925666383

**Comment by danieldunderfelt** [comment]
This should now be fixed. Looks like it was caused by some stops not being found in the database, so the data contained an error. I excluded null stops from the query.
