### ISSUE TITLE
Timetable problem with line 171

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#284]
For example 11:05 and 12:05 are not real journeys. Clicking those takes you to direction 1 journeys.

https://dev-transitlog.hsldev.com/?vehicle=&mapView=60.139795424974196%2C24.589805603027344%2C12&line=6171&route.routeId=6171&route.direction=2&live=false&time=10%3A20%3A00

**Comment by danieldunderfelt** [comment]
This is weird, I'll investigate.

**Comment by danieldunderfelt** [comment]
Fixed on the server! The departures were not being filtered by the route direction properly.
