### ISSUE TITLE
30hr problem is back (with server?)

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#287]
F.ex. 550 direction 1 14.4. is missing data from journeys after 24:00. I see that journeys are driven, with 3 different vehicles so should not be data problem

![image](https://user-images.githubusercontent.com/39256978/56198054-c9b98f00-6042-11e9-8270-5b43ae2e602c.png)
![image](https://user-images.githubusercontent.com/39256978/56198074-d3db8d80-6042-11e9-80ef-038c0b3919e3.png)

https://dev-transitlog.hsldev.com/?line=2550&route.routeId=2550&route.direction=1&mapView=60.18929035036874%2C24.941106355876354%2C12&time=08%3A12%3A12&vehicle=&stop=&tab=journeys_by_week&date=2019-04-09

**Comment by danieldunderfelt** [comment]
I'll have a look!

**Comment by danieldunderfelt** [comment]
This is now fixed.
