### ISSUE TITLE
Last stop event missing - wrong time in arrival time

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#289]
https://dev-transitlog.hsldev.com/journey/20190416/074300/4411/2/0012_1820?line=4411&route.routeId=4411&route.direction=2&mapView=60.172486592339105%2C24.938900470733646%2C16&time=07%3A43%3A00&vehicle=0012%2F1820&stop=&tab=journeys_by_week&date=2019-04-16&live=false&mapOverlays=Stop+radius

![image](https://user-images.githubusercontent.com/39256978/56204299-c7a9fd00-604f-11e9-9d59-6d8559aee8d9.png)

**Comment by danieldunderfelt** [comment]
I can't really reproduce this anymore, but I suspect that the `next_stop_id` has changed to `1020128` at that point. The times work with the data we currently have.

**Comment by samijuhani** [comment]
https://dev-transitlog.hsldev.com/journey/20190528/085200/4411/2/0012_1824?mapView=60.177278350000954%2C24.929652214050297%2C16&route.routeId=4411&route.direction=2&route.originStopId=4150262&date=2019-05-28&vehicle=0012%2F1824&live=false&time=09%3A47%3A03&mapOverlays=Stop+radius 
reproduced here if you could check why

**Comment by danieldunderfelt** [comment]
It seems to be because the doors didn't open at the last stop. Let's wait for HFP 2.0 and use it for the stop times and return to bugs like these when it is implemented.

**Comment by danieldunderfelt** [comment]
@samijuhani this can probably be closed.
