### ISSUE TITLE
2 different planned journey times in one journey details

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#290]
https://dev-transitlog.hsldev.com/journey/20190415/101600/6172/2/0018_889?line=6172&route.routeId=6172&route.direction=2&mapView=60.12835144488301%2C24.434494972229007%2C15&time=10%3A16%3A00&vehicle=0018%2F889&stop=&tab=journeys_by_week&date=2019-04-15&live=false&mapOverlays=Stop+radius

![image](https://user-images.githubusercontent.com/39256978/56204800-f7a5d000-6050-11e9-89af-beb93e19985c.png)

**Comment by danieldunderfelt** [comment]
This is a tricky one as it doesn't happen locally even though I imported the latest JORE data. It is very difficult to debug on the server. I'll try to change how journey departures are fetched, but I don't know what to do more than that.
There is also the issue where extra departures are shown in the weekly view that AFAIK should not be there. That also does not happen for me locally.

**Comment by danieldunderfelt** [comment]
I got access to the production DB locally and that helped me debug this problem. It is fixed now.
