### ISSUE TITLE
Stop names are route names

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#297]
https://dev-transitlog.hsldev.com/journey/20190423/073000/2531/1/0018_873?vehicle=0018%2F873&live=false&date=2019-04-23&mapView=60.17763583619163%2C24.759750366210938%2C12&time=07%3A30%3A00&line=2531&route.routeId=2531&route.direction=1

![image](https://user-images.githubusercontent.com/39256978/56560213-77312300-65ac-11e9-8774-f36018348bce.png)

**Comment by danieldunderfelt** [comment]
Whoops, I mixed up the `name` columns in JORE. Easy fix, coming soon!

**Comment by danieldunderfelt** [comment]
This is now fixed.
