### ISSUE TITLE
Timing stop indicator missing from left side panel

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#299]
![image](https://user-images.githubusercontent.com/39256978/56572122-1531e700-65c7-11e9-9aee-66e2af02e322.png)

https://dev-transitlog.hsldev.com/?vehicle=&live=false&mapView=60.19829339314884%2C24.93758082389832%2C19&time=12%3A53%3A24&stop=1173104

**Comment by danieldunderfelt** [comment]
This is now fixed.
