### ISSUE TITLE
Route filter is too slow

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#300]
As filter searcehs after every input, it is too slow to use atm

![image](https://user-images.githubusercontent.com/39256978/56637976-a3fd3d00-6675-11e9-9eb9-8fe7921e4dcc.png)

**Comment by samijuhani** [comment]
Also search "551" does not give anything though stop has 551 journeys.

**Comment by danieldunderfelt** [comment]
I'll have a look at some point!
