### ISSUE TITLE
Stop order messed after 00:00

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#301]
Also crashes when I click show more stops

https://dev-transitlog.hsldev.com/journey/20190423/234600/1041/1/0012_1607?vehicle=0012%2F1607&mapView=60.208297%2C24.896901%2C17&line=1041&route.routeId=1041&route.direction=1&live=false&time=24%3A00%3A51&date=2019-04-23&time_increment=1

https://dev-transitlog.hsldev.com/journey/20190423/233100/1069/1/0045_1262?vehicle=0045%2F1262&mapView=60.16943935391031%2C24.932613372802738%2C12&line=1069&route.routeId=1069&route.direction=1&live=false&time=23%3A31%3A00&date=2019-04-23&time_increment=1

**Comment by danieldunderfelt** [comment]
I'll take a look!

**Comment by danieldunderfelt** [comment]
This is now fixed. The order of the stops had gotten messed up on the server.
