### ISSUE TITLE
Kauniaisten asema not as a timing stop in stop list

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#306]
This journey has it as a normal stop, other journeys are fine https://dev-transitlog.hsldev.com/journey/20190430/072200/2533/2/0022_977?vehicle=0022%2F977&mapView=60.20701109665714%2C24.729967117309574%2C14&live=false&date=2019-04-30&time=07%3A22%3A00&line=2533&route.routeId=2533&route.direction=2 

![image](https://user-images.githubusercontent.com/39256978/56942346-cfbf6d80-6b22-11e9-8818-045ede9590a6.png)

**Comment by danieldunderfelt** [comment]
This is now fixed.
