### ISSUE TITLE
Part of route missing

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#310]
https://dev-transitlog.hsldev.com/?mapView=60.25818571957642%2C24.84816670417786%2C16&route.routeId=4560&route.direction=1&route.originStopId=1541193 

![image](https://user-images.githubusercontent.com/39256978/57284963-81761580-70b2-11e9-9bca-45f2a155c615.png)

**Comment by danieldunderfelt** [comment]
Is the stop in the right place? These lines come directly from JORE, but I'll make sure that all segments of the line are returned from the server correctly.

**Comment by samijuhani** [comment]
Yeah looks fine in journey planner https://reittiopas.hsl.fi/linjat/HSL:4560/pysakit/HSL:4560:0:01

**Comment by danieldunderfelt** [comment]
Okay I'll investigate.

**Comment by danieldunderfelt** [comment]
This is how it comes out from our JORE database. Not sure how to fix, let's see if it resolves itself after a few imports.

**Comment by danieldunderfelt** [comment]
This is not fixed yet. I spoke with the Digitransit people and they do a lot more than we do to match the route line to the actual road on the map. How does this part of the route look in JORE?

**Comment by samijuhani** [comment]
![image](https://user-images.githubusercontent.com/39256978/57676062-58163600-762c-11e9-93de-d507da645d55.png)

**Comment by danieldunderfelt** [comment]
Okay, so it looks like a problem with the validity dates. Again.

**Comment by danieldunderfelt** [comment]
This is now fixed.
