### ISSUE TITLE
Driving time(?) as departure time

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#312]
https://dev-transitlog.hsldev.com/journey/20190506/162800/4739/1/0022_616?mapView=60.35811556066257%2C25.147866010665897%2C16&route.routeId=4739&route.direction=1&route.originStopId=1020115&vehicle=0022%2F616&live=false&time=17%3A39%3A09&date=2019-05-06

**Comment by danieldunderfelt** [comment]
Not sure what this refers to. Which time do you mean?

**Comment by samijuhani** [comment]
![image](https://user-images.githubusercontent.com/39256978/57286053-cc912800-70b4-11e9-9510-c49affb7f322.png)

**Comment by danieldunderfelt** [comment]
This is the same issue where events with the `next_stop_id` parameter appear after the journey has ended. HFP 2.0 data should solve it.

**Comment by samijuhani** [comment]
Ok. Closing as data issue.
