### ISSUE TITLE
Update does not update timetables data

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#314]
https://dev-transitlog.hsldev.com/journey/20190509/053200/2551/2/0012_1610?vehicle=0012%2F1610&mapView=60.19829939190643%2C24.937366247177128%2C17&stop=1173104&language=en&route.routeId=2551&route.direction=2&route.originStopId=2231225&live=false&time=08%3A05%3A23&date=2019-05-09&tab=timetables here I press update, no new data in timetables table

**Comment by danieldunderfelt** [comment]
There is already an issue about this (#292) and as I stated there, the week view is cached for 5 minutes. It's a heavy view to create and not really useful for real-time data, so a longer cache period is good to use in my opinion.

**Comment by samijuhani** [comment]
This is about stop timetables view that has worked earlier.

**Comment by danieldunderfelt** [comment]
Oh, sorry! I read that wrong. But those are also cached for 5 minutes as the view is relatively heavy as well.

**Comment by danieldunderfelt** [comment]
I have been adjusting the cache times periodically so if it worked for you a while ago I might have changed it since. Or you just refreshed after the cache timeout.

**Comment by samijuhani** [comment]
This does not have to do with time as i now press update after an hour, no effect to timetables bar on left.

**Comment by danieldunderfelt** [comment]
Okay, I'll have a look.

**Comment by danieldunderfelt** [comment]
This is now fixed. The timetable query was not listening to "update" actions.
