### ISSUE TITLE
Sorting in stop search

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#317]
Needed to search stop H1222. Old habit is to search helsinki stops without H. Thinking we should priorize short stop numbers over long ones in this search, for example 
![image](https://user-images.githubusercontent.com/39256978/57601764-1327cc00-7566-11e9-8303-343dc89417f5.png)

**Comment by danieldunderfelt** [comment]
Yes, I can see what I can do. In this case, the Espoo stops would come before the Helsinki stops though.

**Comment by danieldunderfelt** [comment]
I adjusted the search logic slightly and now the Helsinki stop is first, but the rest of the *1222 stops are lower down. This is because previously, they got their high match number from also having "1222" in the longer stop ID, but now I emphasize the shortId more in the stop search. I'll continue fiddling with the logic a bit.

**Comment by samijuhani** [comment]
Good. This should be fine because usually if you input 2-4 numbers you are using short number. If input more, previous logic does not matter anymore and you in most cases input the whole 7 numbers.

**Comment by samijuhani** [comment]
Still a bit unlogical but let's poke this later maybe after more urgent things are done
![image](https://user-images.githubusercontent.com/39256978/58149731-c67e7800-7c6c-11e9-82d8-c9e1ff7a539f.png)

**Comment by danieldunderfelt** [comment]
Yeah, I know. I'll try one more thing now, shouldn't take long.

**Comment by danieldunderfelt** [comment]
The search function is now improved. Note that something is wrong on the server which is why searches may take a while, This is being addressed and is a separate issue.
