### ISSUE TITLE
Go through results of Aalto usability tests and interviews and brake it to tasks

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#323]
[HSL Empirical Evaluation Report.docx](https://github.com/HSLdevcom/transitlog-ui/files/3177572/HSL.Empirical.Evaluation.Report.docx)
[Transitlog Expert evaluation report.docx](https://github.com/HSLdevcom/transitlog-ui/files/3177573/Transitlog.Expert.evaluation.report.docx)

**Comment by th0rgall** [comment]
The final report with a few more ideas will be sent this week!

**Comment by samijuhani** [comment]
@ahjyrkia final report here: https://docs.google.com/document/d/1qwRhVNdqJHA3Yeu2N_eWjAJwwLmoZM1eaSOq-UxM-wc/edit?usp=sharing
