### ISSUE TITLE
Minor UI thing with Firefox

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#329]
![image](https://user-images.githubusercontent.com/39256978/57767645-8ff7a900-7712-11e9-944e-3df0748a7569.png)

**Comment by danieldunderfelt** [comment]
The floating table header needs to make room for the scrollbar, and annoyingly scrollbar styling is drastically different between browsers and impossible on Firefox. I changed the scrollbar width on Chrome to match Firefox, but apparently they have changed the width of the scrollbar for some reason. I'll see if there is another way to implement this.

**Comment by samijuhani** [comment]
Very small clitch so this can be left to see later.
