### ISSUE TITLE
Stop popup too big

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#332]
Let's think about this but maybe we should make it max height N and scrollable for starts.

![image](https://user-images.githubusercontent.com/39256978/58014193-edb83680-7b00-11e9-8c3b-7c59e3f43f2b.png)

**Comment by danieldunderfelt** [comment]
Yes, this is how it already works. I will lower the maxHeight setting on the popup. There also seems to be a bug somewhere in Leaflet where the maxHeight is not applied to the stop popups which I think is what you're seeing. I'll see if there is a work-around.
