### ISSUE TITLE
Can't verify phone number in ID registration

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#335]
![image](https://user-images.githubusercontent.com/39256978/58089554-bcf20300-7bcd-11e9-86cc-53a8edfd16b2.png)

**Comment by samijuhani** [comment]
Works without phone number

**Comment by danieldunderfelt** [comment]
Jere is checking this later today. We could not change the setting ourselves in the admin dashboard.

**Comment by danieldunderfelt** [comment]
This should now be fixed.
