### ISSUE TITLE
Tooltip language does not switch on language switch

### ISSUE THREAD

**Issue by th0rgall** [HSLdevcom/transitlog-ui#337]
The hover-tooltip translations (`title` attributes on HTML elements) stay in the original language when the language is switched from FI -> EN (and any other switch).

They do load correctly when the page is refreshed with `&language=en` (or any other language) in the URL.

**Comment by danieldunderfelt** [comment]
Good catch! This is probably because the place where the tooltips are attached to the elements are not all inside observer regions. We should also actually add tooltips in other languages and for more elements. Now there are only three in english and none in swedish.
