### ISSUE TITLE
Planned stop times incorrect at stop H1011 on journey stop list

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#338]
All stop times are incorrect https://dev-transitlog.hsldev.com/?mapView=60.16465712803696%2C24.91321563720703%2C12&route.routeId=2146A&route.direction=1&route.originStopId=1040281&date=2019-05-21&live=false&time=15%3A42%3A51&stop=1201229&vehicle=0018%2F272

![image](https://user-images.githubusercontent.com/39256978/58228153-5d633700-7d36-11e9-9f5e-0cc7001b3e71.png)

**Comment by danieldunderfelt** [comment]
I will investigate.

**Comment by danieldunderfelt** [comment]
This is now fixed!
