### ISSUE TITLE
Stop search is broken

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#345]
Can not get almost any search example thses give no result: kappatie 1583 lasipalatsi

**Comment by danieldunderfelt** [comment]
This is now fixed. It was due to a optimization that limited the number of stops that were returned from the server as they are quite many. I moved the stop search to the UI to make it much quicker, but I forgot this optimization in place.

**Comment by samijuhani** [comment]
Great it's also fast again
