### ISSUE TITLE
Validate JORE data consistently

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#346]
Still case here unfortunately https://dev-transitlog.hsldev.com/journey/20190527/123000/1073/1/0030_25?date=2019-05-27&route.routeId=1073&route.direction=1&route.originStopId=1111151&live=false&mapView=60.17966863144996%2C24.95222568511963%2C16&time=12%3A46%3A17&vehicle=0030%2F25

![image](https://user-images.githubusercontent.com/39256978/58413705-2072a980-8082-11e9-809d-e0ef5d968790.png)

**Comment by danieldunderfelt** [comment]
I don't have a good solution for these as the date chains didn't work in all cases. I'm afraid that the JORE data model is not really compatible with historical data. Maybe we can sit down with Petri Selkisalo and try to figure out a solution?

**Comment by samijuhani** [comment]
Let's live with it for now and come back to it

**Comment by danieldunderfelt** [comment]
Agreed!

**Comment by danieldunderfelt** [comment]
This is now fixed.
