### ISSUE TITLE
User wants to see what direction a stop has journeys in stop search

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#349]
User asked if search results could indicate to what direction stop is so one should not have to click it to find out. As directions of routes are not the same always, could we show routes and directions of stop maybe as tooltip when hovering over stop in search result?

![image](https://user-images.githubusercontent.com/39256978/58477234-b7f7fb00-815b-11e9-8aef-71e796920802.png)

**Comment by danieldunderfelt** [comment]
I would think twice about this. There are a lot of stops, and sending them over the network is already heavy. Many stops have a lot of routes, which would add to the data. Also, then you would need to fetch and cache the stops with a date, adding to the complexity of the least complex query we currently have.

I can try adding the routes and see how the stop query is impacted.

**Comment by samijuhani** [comment]
Yep see if it is possible without affecting speed. Other ways to solve the need are welcome to be proposed also.

**Comment by danieldunderfelt** [comment]
It seems to work well enough, so expect this to land in a coming update.

**Comment by danieldunderfelt** [comment]
I also added an icon next to the route when the stop is a timing stop for that route. I hope it will be useful!
