### ISSUE TITLE
Crash when opened weekly view

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#351]
This crashes after a bi of loading.

https://dev-transitlog.hsldev.com/journey/20190528/200200/2551/2/0012_1111?mapView=60.16892700585851%2C24.804382324218754%2C12&stop=1173104&showInstructions=false&route.routeId=2551&route.direction=2&route.originStopId=&vehicle=0012%2F1111&live=false&time=19%3A58%3A52&tab=journeys_by_week&date=2019-05-28

**Comment by danieldunderfelt** [comment]
Found the bug, should be fixed now! We should really have made the UI with Typescript, it would have caught most of the bugs that cause these crashes.
