### ISSUE TITLE
Plan how to show deadruns

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#353]
1. Simple use case is to show it via vehicle search
2. More complex is going via route/other search, how to show deadruns when journey data ends/before it begins.

**Comment by danieldunderfelt** [comment]
We could have a sidebar panel that shows the current deadrun journeys, and when it is active they are drawn on the map. The downside is that we can't fit in more tabs, so we need to also come up with a new solution for those.

**Comment by samijuhani** [comment]
Need to draw that idea to understand. Have been thinking only map is needed for this with tooltip as now.

**Comment by samijuhani** [comment]
Planning was done in daily 19.6. Implementation issue is https://github.com/HSLdevcom/transitlog-ui/issues/366
