### ISSUE TITLE
Route is not drawn correctly after route change on 2502

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#355]
https://dev-transitlog.hsldev.com/journey/?mapView=60.18406329737213%2C24.926433563232425%2C15&route.routeId=2502&route.direction=1&route.originStopId=1100101&mapOverlays

![image](https://user-images.githubusercontent.com/39256978/58788316-5240be80-85f4-11e9-9aa6-52168d492862.png)

**Comment by danieldunderfelt** [comment]
This is now fixed.
