### ISSUE TITLE
1002 route problem

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#356]
With route 1002 can happen that stops change place but route stays. Reproducable by changing day between today and yesterday. Route changed today. Data also missing on some cases when date is changed.

![image](https://user-images.githubusercontent.com/39256978/58788379-756b6e00-85f4-11e9-9718-0c7620f10fdc.png)

**Comment by danieldunderfelt** [comment]
This seems to be fixed.
