### ISSUE TITLE
Add hover functionality to stops in map

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#359]
From Aalto: "*Participants also tend to rely on the filter fields. When the results are filtered and doesn't give the information they need, then they turn their attention on the map. If the map doesn't help, they either quickly go through the sidebar list, or just go to Reittiopas for further information searching.*

>*Interestingly, when checking for the bus stop, two of the participants fell back on Reittiopas while this was not necessary. This suggests they want to use a more familiar system rather than experimenting on a new system.*"

**Comment by samijuhani** [comment]
Not seeing this functionality?

**Comment by danieldunderfelt** [comment]
I'm not sure what the functionality is. The stops are highlighted on the map when hovering over the stops in the sidebar when a journey is selected. Is this about something else?

**Comment by samijuhani** [comment]
Show stop information (name, id's) as tooltip when hovering over stop in map. Without clicking.
