### ISSUE TITLE
Make searches filter each other

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#360]
Could example stop search have be filtered if user has already searched route. Would answer Aalto: "*Task 1: Find the bus number 24 to seurasaari which started at 15:05. Participants filtered from the empty (starting) state of the system to make it display the information related to the delay of a bus line in a given direction for a certain time. (The system would thus show 3 pieces of information upon adding the filters)*

>*Task 1a: Is there a delay in the Kolmikulma station for that route*"

**Comment by danieldunderfelt** [comment]
I wouldn't make the searches filter each other, since that would block the user from opening a stop that isn't part of the selected route. But we can list the route stops in the sidebar before a departure is selected. As far as I've understood it, that would solve this use case.

**Comment by samijuhani** [comment]
That would make sense as the tab is open anyway, just empty now. Later.

**Comment by danieldunderfelt** [comment]
I already implemented it, didn't take very long.

Visible in dev.
