### ISSUE TITLE
Multilingual alerts

### ISSUE THREAD

**Issue by danieldunderfelt** [HSLdevcom/transitlog-ui#369]
Show alerts in the correct language per the current language setting.

**Comment by samijuhani** [comment]
Works at start but after few language changes one language stays.

**Comment by samijuhani** [comment]
And by "stays" means alert language does not change after third time language is changed. UI changes fine.

**Comment by danieldunderfelt** [comment]
This should be fixed now.

**Comment by samijuhani** [comment]
Yes not able to reproduce anymore
