### ISSUE TITLE
Cancelled journey shown on wrong time

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#370]
This journey is 7:25-8:08 but it is now shown at 14:41.

Expected: Shown only 7:25-8:08.

![image](https://user-images.githubusercontent.com/39256978/60263871-6ffafe00-98ea-11e9-9048-e779fe74cac6.png)

**Comment by danieldunderfelt** [comment]
Cancellations are currently shown for the whole day, yes. Alerts have valid_from and valid_to properties which cancellations do not have, so it's not as clear when to show or hide cancellations. What should the logic be here? Within how many hours of the journey time should the cancellation be shown?

**Comment by samijuhani** [comment]
Oh need to think. That. Moving back to backlog for now.

**Comment by samijuhani** [comment]
Cancellations and alerts are shown the whole day nowadays
