### ISSUE TITLE
Details for cancelled journeys should only show for own company after login

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#371]
+HSL

**Comment by samijuhani** [comment]
Works for HSL, still to be tested with operator user after that is implemented

**Comment by samijuhani** [comment]
Tested to work as planned in dev. Close after prod deployment

**Comment by danieldunderfelt** [comment]
Everything should be in prod now, but you'd need an actual operator login to test as dev login is not enabled.

**Comment by samijuhani** [comment]
I'll ask one to test and close after that when tested to work.

**Comment by samijuhani** [comment]
Operator used confirmed works as planned in prod also.
