### ISSUE TITLE
dev.reittiloki.hsl.fi: Show only selected routes alerts

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#378]
Show only alerts and cancellations for line 550 when viewing line 550. Also map should show alert icons for stops only when alert is for a stop. No route alerts in map.

![image](https://user-images.githubusercontent.com/39256978/64010683-f3231500-cb22-11e9-85fc-5a7d820a67b0.png)

**Comment by samijuhani** [comment]
In fact looks like all stops have info and disruption icons at the moment.

**Comment by danieldunderfelt** [comment]
A part of the problem is that the alerts are scoped to "all routes" or "all stops" which is why they show up on all stops. I'll remove route alerts from stops and make sure only the selected route alerts are shown in the sidebar, but for the other issues we have to fix the data.
