### ISSUE TITLE
dev.reittiloki.hsl.fi: Area search takes too long and crashed

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#379]
Works eventually. Time sliding is slow. Optimize it.

**Comment by danieldunderfelt** [comment]
This seems to be a limitation of the HFP database, along with a timeout error. I'll look into increasing the  timeout, but don't expect too much speed from this feature.

**Comment by samijuhani** [comment]
Maybe we lower the default time for the search from 60 to start if seems a problem.

**Comment by danieldunderfelt** [comment]
The area search will now complete without timing out. It is not advised to search for a large area in a busy location...

**Comment by samijuhani** [comment]
Tested to work ok.
