### ISSUE TITLE
dev.reittiloki.hsl.fi: Line 415 missing from route search

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#380]

**Comment by danieldunderfelt** [comment]
Do you mean this one? https://dev.reittiloki.hsl.fi/journey/20190830/053600/3001I/1/0090_1001?mapView=60.24458245426549%2C24.953384399414066%2C11&time=06%3A34%3A40&route.routeId=4415&route.direction=1&route.originStopId=1020239&vehicle=0090%2F1001&live=false

**Comment by samijuhani** [comment]
Working now, must have been the new jore import
