### ISSUE TITLE
Timing stop icon is not visualized like other stops for doors-not-opened

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#382]

**Comment by samijuhani** [comment]
Still missing here:

https://reittiloki.hsl.fi/journey/20190917/062000/1500/1/0018_608?route.routeId=1500&route.direction=1&route.originStopId=1453184&mapView=60.193818681052385%2C25.02960205078125%2C18&areaBounds=&live=false&time=06%3A30%3A01&areaEventsStyle=markers&mapBaseLayer=Aerial&stop=1173125&vehicle=0018%2F608

![image](https://user-images.githubusercontent.com/39256978/65034325-792ac280-d94f-11e9-93f2-a1b08b81f6d1.png)

**Comment by danieldunderfelt** [comment]
It is fixed, you were looking at an older version.
