### ISSUE TITLE
Not seeing past days journey information in left side panel

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#384]
Data itself is there and seen in map.

![image](https://user-images.githubusercontent.com/39256978/64153805-41dcf180-ce38-11e9-9687-32d51b9e8dbe.png)

**Comment by samijuhani** [comment]
Same in prod now when i look 13.9. and 12.9.

![image](https://user-images.githubusercontent.com/39256978/64936335-0392f980-d85e-11e9-827e-8d58ae88d212.png)

**Comment by samijuhani** [comment]
Haven't seen this anymore, closable?

**Comment by danieldunderfelt** [comment]
Yeah, this was probably a temporary error and can be closed.

**Comment by samijuhani** [comment]
In fact this looks also a bit like #406 closing as non-reproducible and duplicate.
