### ISSUE TITLE
502 Bad gateway

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#387]
Seeing this quite often when searching 

![image](https://user-images.githubusercontent.com/39256978/64170434-c8a1c680-ce58-11e9-9b3e-5fd69b36c53a.png)

**Comment by samijuhani** [comment]
Seems to happen after changing date. With F5 works again.

**Comment by samijuhani** [comment]
Must be timeout?

**Comment by danieldunderfelt** [comment]
This can happen at times before we have a fast enough database. Closing for now.
