### ISSUE TITLE
Add planned link meters to transitlog

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#388]
From jore add route link lengths in meters to transitlog. Make those as a layer, default off. Seeable only for HSL user.

**Comment by samijuhani** [comment]
Let's see later if need is still relevant

**Comment by danieldunderfelt** [comment]
This is now coming to dev.

To view the lengths, select a route and then select the "Route segment lengths" layer in the map layer selector. Zooming in will clear up the mess of tooltips.

The lengths are displayed per stop from the previous stop. Also displayed is the total route length up to the current stop as well as the total planned drive duration up to the current stop.

**Comment by samijuhani** [comment]
Think we need de-clutter the view from outer zoom level. Suggestions? Whole route-level is too much atm

**Comment by samijuhani** [comment]
Keeping in review until we get back to this

**Comment by danieldunderfelt** [comment]
Comments from Petri (transitlog-feedback):

1. Miten ensimmäisellä pysäkillä voi olla etäisyys edelliseen pysäkkiin? Toisaalla taas toiseksi ja kolmanneksi viimeisellä pysäkillä etäisyystieto on täsmälleen sama.
2. "viime"-sana ("Pituus viime pysäkiltä"-teksti) viittaa ajallisesti menneisyyteen ja koska tässä tapauksessa viitataan spatiaaliseen tietoon ei ko. sana ole äidinkielisesti oikein. "Edelliseltä" tai "Ed." toimii paremmin.
3. Tietolaatikot sattuvat aika usein menemään toistensa päälle. Jos laatikot väistäisivät toisiansa...
4. Tekninen/Suunnitelullinen huomoi: Kaikille pysäkeille ei suunnitelle ajoaikoja. Ajoajat suunnitellaan ns. Hastus-pysäkeille, joita linjalla voi olla 2...N kappaletta. Hastus-pysäkkien väliin jäävät pysäkkitiedot approksimoidaan painotuksilla suunnitellusta ajoajasta. Joten tietolaatikoissa kuuluisi lukea "Suunniteltu ajoaika" vain Hastus-pysäkeillä ja muilla "Arvioitu/Approksimoitu ajoaika".
5. Ajoaika on ajallisesti riippuvainen eli aikaisin aamulla on eri ajoaika kun illan ruuhkassa. Nyt ajoaika vaikuttaa olevan vakiotieto. Ja kun ajoaika-tietoa vertailee pysäkkiaikojen eroihin voi huomata niissä olevan useammankin minuutin ero mikä on todellisuudessa suunniteltu. Eli "Suunniteltu ajoaika"-tieto pitäisi itse asiassa laskea pysäkin aikataulutietojen mukaan, jokaiselle lähdölle erikseen.

Changes made based on the feedback:

1. Removed the info box from the first stop. Petri is correct in that it doesn't provide any useful information.
2. I fixed the "viime" word, it is now "ed." as suggested.
3. Probably technically possible, but we are using Leaflet functionality and a light implementation, so this would take some effort to do.
4. Reittiloki doesn't know anything about "Hastus stops".
5. Removed the "suunniteltu ajoaika" row completely, as Petri suggested it is not relevant or useful.
