### ISSUE TITLE
Hide cancelled journey description behind login + reason fixes

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#390]
Common user can not see the written description of cancelled journey. Nor reasons at all. Only HSL user or operator user can see those. Also lets write categories and effects as proper language. Will give the terms to use.

![image](https://user-images.githubusercontent.com/39256978/64694126-a552c900-d4a1-11e9-967b-a656342c42be.png)

**Comment by samijuhani** [comment]
"category" : {
            "ACCIDENT" : "Liikennevahinko",
            "ASSAULT" : "Häiriköinti/ilkivalta",
            "NO_DRIVER" : "Tuotanto-/Suunnitteluvirhe",
            "VEHICLE_SHORTAGE" : "Ajoneuvo puuttuu",
            "VEHICLE_BREAKDOWN" : "Ajoneuvorikko",
            "WRONG_ROUTE" : "Ajettu väärää reittiä",
            "WEATHER" : "Huono ajokeli",
            "STRIKE" : "Työtaistelutoimenpide",
            "OTHER" : "Muu syy",
            "VEHICLE_OFF_THE_ROAD": "Kulkutie/Suistuminen/Ruuhka",
            "SEIZURE": "Sairaskohtaus/Loukkaantuminen",
            "ITS_SYSTEM_ERROR": "LIJ-järjestelmän ongelma/käyttövirhe",
            "TOO_MANY_PASSENGERS": "Liikaa matkustajia",
            "OTHER_DRIVER_ERROR" : "Kuljettajan virhe",
            "EARLIER_DISRUPTION": "Aikaisempi häiriö",
            "NO_TRAFFIC_DISRUPTION": "Ei liikennehäiriötä",
            "TRACK_BLOCKED": "Este raiteilla",
            "STAFF_DEFICIT": "Henkilöstövaje",
            "DISTURBANCE": "Järjestyshäiriö",
            "VEHICLE_DEFICIT": "Kalustovaje",
            "ROAD_CLOSED": "Katu suljettu",
            "ROAD_TRENCH": "Katukaivanto",
            "TRACK_MAINTENANCE": "Kiskotyöt",
            "TRAFFIC_ACCIDENT": "Onnettomuus",
            "TRAFFIC_JAM": "Ruuhka",
            "MEDICAL_INCIDENT": "Sairaustapaus",
            "WEATHER_CONDITIONS": "Sääolosuhteet",
            "TECHNICAL_FAILURE": "Tekninen vika",
            "TEST": "Testiviesti",
            "ROAD_MAINTENANCE": "Tietyö",
            "SWITCH_FAILURE": "Vaihdevika",
            "STATE_VISIT": "Valtiovierailu",
            "POWER_FAILURE": "Virtahäiriö",
            "MISPARKED_VEHICLE": "Väärin pysäköity auto",
            "PUBLIC_EVENT": "Yleisötapahtuma"
        },
        "subcategory": {
            "ASSAULT_ON_DRIVER": "Kohdistunut kuljettajaan",
            "ASSAULT_ON_PASSENGER": "Kohdistunut matkustajaan",
            "ASSAULT_ON_VEHICLE": "Kohdistunut kalustoon",
            "BREAK_MALFUNCTION": "Jarruvika/paineilmavuoto",
            "CONGESTION_CAUSED_BY_ACCIDENT": "Ruuhka (ulkopuolisesta syystä, kolari/yleisötapahtuma yms.)",
            "CONGESTION_CAUSED_BY_WEATHER": "Huonosta kelistä johtuva ruuhka ja hidas eteneminen",
            "CONGESTION_REASON_UKNOWN": "Ruuhka (hidastumiselle ei tiedossa erityistä syytä)",
            "CORRECT_ROUTE_BLOCKED": "Tietyö/kolari/yms. estänyt oikean reitin ajamisen",
            "DEVICE_ERROR": "Laite rikki",
            "DOOR_MALFUNCTION": "Ovivika",
            "DRIVER_ERROR": "Kuljettajan virhe",
            "DRIVER_LATE": "Kuljettaja myöhässä",
            "DRIVER_SEIZURE": "Kuljettajan sairastuminen/sairaskohtaus",
            "ELECTRIC_MALFUNCTION": "Sähkövika",
            "ENGINE_MALFUNCTION": "Moottorin häiriö",
            "FALSE_ALARM": "Väärä hälytys",
            "FAULT_UNKNOWN": "Syyllisyys epäselvä",
            "FLUID_LEAKAGE": "Neste-/Polttoaine-/Voiteluainevuoto",
            "INSUFFICIENT_CAPASITY": "Kapasiteetti ei riittävää",
            "INSUFFICIENT_INSTRUCTIONS_BY_AUTHORITY": "Väärä/puutteellinen ohjeistus (tilaaja)",
            "INSUFFICIENT_INSTRUCTIONS_BY_OPERATOR": "Väärä/puutteellinen ohjeistus (liikennöitsijä)",
            "ITS_SYSTEM_NOT_INSTALLED": "Autossa ei asennettuna LIJ-laitetta",
            "ND_OPERATOR_PLANNING_ERROR": "Liikennöitsijän suunnitteluvirhe",
            "NO_VEHICLE_AVAILABLE": "Ajoneuvopula",
            "OPERATOR_DEVICE_ERROR": "Laite rikki, liikennöitsijän vastuulla",
            "OPERATOR_PERSONNEL_ON_STRIKE": "Liikennöitsijän henkilökunta",
            "OPPOSITE_FAULT": "Vastapuolen syy",
            "OTHER_ASSAULT": "Muu",
            "OTHER_MALFUNCTION": "Muu vika",
            "OTHER_OPERATOR_REASON": "Liikennöitsijästä riippuva",
            "OTHER_SEIZURE": "Muu syy",
            "OTHER_STRIKE": "Muu",
            "OTHER_ITS_ERROR": "Muu vika",
            "OUT_OF_FUEL": "Polttoaine loppu",
            "OWN_FAULT": "Oma syy",
            "PASSED_OUT_PASSENGER": "Päihtynyt matkustaja",
            "PASSENGER_INJURED": "Matkustajan loukkaantuminen",
            "PASSENGER_SEIZURE": "Matkustajan sairastuminen/sairaskohtaus",
            "ROAD_BLOCKED": "Tie poikki, tietyö/kolari/yleisötapahtuma yms.",
            "STAFF_SHORTAGE": "Henkilökuntapula",
            "STUCK_CAUSED_BY_SLIPPERY": "Jumissa liukkauden takia",
            "UNDRIVEABLE_CONDITIONS": "Tie ei sään takia ajokelpoinen (liukkaus yms.)",
            "UNKNOWN_CAUSE": "Ulkopuolinen syy",
            "USER_ERROR": "Kuljettajan LIJ-käyttövirhe",
            "VEHICLE_OFF_THE_ROAD_BY_DRIVER_ERROR": "Auto jumissa ajovirheen takia",
            "VEHICLE_OFF_THE_ROAD_BY_OTHER_REASON": "Auto jumissa muusta syystä",
            "VS_OPERATOR_PLANNING_ERROR": "Liikennöitsijän suunnitteluvirhe",
            "WRONG_INFORMATION_IN_DEVICE": "Laitteessa väärät lähdöt",
            "SLIPPERY_TRACK": "Liukkaat kiskot (lehtikeli)",
            "MISSPARKED_VEHICLE" : "Väärin pysäköity auto"
        }

        "category" : {
            "ACCIDENT" : "Accident",
            "ASSAULT" : "Assault",
            "NO_DRIVER" : "Planning error",
            "VEHICLE_SHORTAGE" : "Vehicle shortage",
            "VEHICLE_BREAKDOWN" : "Vehicle breakdown",
            "WRONG_ROUTE" : "Wrong route",
            "WEATHER" : "Weather",
            "STRIKE" : "Strike",
            "OTHER" : "Other",
            "VEHICLE_OFF_THE_ROAD": "Vehicle off the road",
            "SEIZURE": "Seizure",
            "ITS_SYSTEM_ERROR": "LIJ-System error",
            "TOO_MANY_PASSENGERS": "Too many passengers",
            "OTHER_DRIVER_ERROR" : "Other driver error",
            "EARLIER_DISRUPTION": "Earlier disruption",
            "NO_TRAFFIC_DISRUPTION": "No traffic disruption",
            "TRACK_BLOCKED": "Track blocked",
            "STAFF_DEFICIT": "Staff decifit",
            "DISTURBANCE": "Disturbance",
            "VEHICLE_DEFICIT": "Vehicle deficit",
            "ROAD_CLOSED": "Road closed",
            "ROAD_TRENCH": "Road trench",
            "TRACK_MAINTENANCE": "Track maintenance",
            "TRAFFIC_ACCIDENT": "Traffic accident",
            "TRAFFIC_JAM": "Traffic jam",
            "MEDICAL_INCIDENT": "Medical incident",
            "WEATHER_CONDITIONS": "Weather conditions",
            "TECHNICAL_FAILURE": "Technical failure",
            "TEST": "Test",
            "ROAD_MAINTENANCE": "Road maintenance",
            "SWITCH_FAILURE": "Switch failure",
            "STATE_VISIT": "State visit",
            "POWER_FAILURE": "Power failure",
            "MISPARKED_VEHICLE": "Misparked car",
            "PUBLIC_EVENT": "Public event"
        },
        "subcategory": {
            "ASSAULT_ON_DRIVER": "Assault on driver",
            "ASSAULT_ON_PASSENGER": "Assault on passenger",
            "ASSAULT_ON_VEHICLE": "Assault on vehicle",
            "BREAK_MALFUNCTION": "Break malfunction",
            "CONGESTION_CAUSED_BY_ACCIDENT": "Congestion (caused by accident)",
            "CONGESTION_CAUSED_BY_WEATHER": "Congestion cause by weather",
            "CONGESTION_REASON_UKNOWN": "Congestion (reason unknown)",
            "CORRECT_ROUTE_BLOCKED": "Correct route blocked",
            "DEVICE_ERROR": "Device error",
            "DOOR_MALFUNCTION": "Door malfunction",
            "DRIVER_ERROR": "Driver error",
            "DRIVER_LATE": "Driver late",
            "DRIVER_SEIZURE": "Driver seizures",
            "ELECTRIC_MALFUNCTION": "Electric malfunction",
            "ENGINE_MALFUNCTION": "Engine malfunction",
            "FALSE_ALARM": "False alarm",
            "FAULT_UNKNOWN": "Fault unknown",
            "FLUID_LEAKAGE": "Fluid leakage",
            "INSUFFICIENT_CAPASITY": "Insufficient capasity",
            "INSUFFICIENT_INSTRUCTIONS_BY_AUTHORITY": "Insufficient instructions (by authority)",
            "INSUFFICIENT_INSTRUCTIONS_BY_OPERATOR": "Insufficient instructions (by operator)",
            "ITS_SYSTEM_NOT_INSTALLED": "LIJ-System not installed",
            "ND_OPERATOR_PLANNING_ERROR": "Operator planning error",
            "NO_VEHICLE_AVAILABLE": "Vehicle available",
            "OPERATOR_DEVICE_ERROR": "Operator device error",
            "OPERATOR_PERSONNEL_ON_STRIKE": "Operator personnel on strike",
            "OPPOSITE_FAULT": "Opposite fault",
            "OTHER_ASSAULT": "Other assault",
            "OTHER_MALFUNCTION": "Other malfunction",
            "OTHER_OPERATOR_REASON": "Other operator reason",
            "OTHER_SEIZURE": "Other seizure",
            "OTHER_STRIKE": "Other strike",
            "OTHER_ITS_ERROR": "Other LIJ-error",
            "OUT_OF_FUEL": "Out of fuel",
            "OWN_FAULT": "Own fault",
            "PASSED_OUT_PASSENGER": "Passed out passenger",
            "PASSENGER_INJURED": "Passenger injured",
            "PASSENGER_SEIZURE": "Passenger seizure",
            "ROAD_BLOCKED": "Road blocked",
            "STAFF_SHORTAGE": "Staff shortage",
            "STUCK_CAUSED_BY_SLIPPERY": "Stuck caused by slippery",
            "UNDRIVEABLE_CONDITIONS": "Undriveable conditions",
            "UNKNOWN_CAUSE": "Unknown cause",
            "USER_ERROR": "User error",
            "VEHICLE_OFF_THE_ROAD_BY_DRIVER_ERROR": "Vehicle off road (by driver error)",
            "VEHICLE_OFF_THE_ROAD_BY_OTHER_REASON": "Vehicle off road (by other reason)",
            "VS_OPERATOR_PLANNING_ERROR": "Operator planning error",
            "WRONG_INFORMATION_IN_DEVICE": "Wrong information in device",
            "SLIPPERY_TRACK": "Slippery track (leawes)",
            "MISSPARKED_VEHICLE" : "Miss parked vehicle"
        }

**Comment by danieldunderfelt** [comment]
This is now live in all environments.

**Comment by samijuhani** [comment]
Please add common language to categories also.

**Comment by danieldunderfelt** [comment]
Translations for cancellation categories is coming. We also need translations for the following alert impacts and cancellation effects:

```
alertImpact:  {
    DELAYED
    POSSIBLY_DELAYED
    REDUCED_TRANSPORT
    CANCELLED
    POSSIBLE_DEVIATIONS
    RETURNING_TO_NORMAL
    DISRUPTION_ROUTE
    DEVIATING_SCHEDULE
    IRREGULAR_DEPARTURES
    IRREGULAR_DEPARTURES_MAX_15
    IRREGULAR_DEPARTURES_MAX_30
    VENDING_MACHINE_OUT_OF_ORDER
    BICYCLE_STATION_OUT_OF_ORDER
    BICYCLE_SYSTEM_OUT_OF_ORDER
    REDUCED_BICYCLE_PARK_CAPACITY
    OTHER
    NO_TRAFFIC_IMPACT
    UNKNOWN
}

cancellationType: {
    CANCEL_DEPARTURE
    DETOUR
    SKIPPED_STOP_CALLS
    EARLY_DEPARTURE
    EARLY_DEPARTURE_FROM_TIMING_POINT
    LATE_DEPARTURE
    DEPARTURED_AFTER_NEXT_JOURNEY
    BLOCK_FIRST_DEPARTURE_LATE
    TIS_ERROR
}

cancellationEffect: {
    CANCEL_ENTIRE_DEPARTURE
    CANCEL_STOPS_FROM_START
    CANCEL_STOPS_FROM_MIDDLE
    CANCEL_STOPS_FROM_END
}
```

**Comment by samijuhani** [comment]
Asked

**Comment by samijuhani** [comment]
"impacts": {
            "DELAYED": "Myöhästyy",
            "POSSIBLY_DELAYED": "Mahdollisesti myöhässä",
            "REDUCED_TRANSPORT": "Harvennettu liikenne",
            "CANCELLED": "Peruttu",
            "POSSIBLE_DEVIATIONS": "Poikkeukset mahdollisia",
            "RETURNING_TO_NORMAL": "Palautumassa normaaliksi",
            "DISRUPTION_ROUTE": "Poikkeusreitti",
            "DEVIATING_SCHEDULE": "Poikkeusaikataulu",
            "IRREGULAR_DEPARTURES": "Epäsäännölliset vuorovälit",
            "IRREGULAR_DEPARTURES_MAX_15": "Epäsäännölliset vuorovälit, odotus enintään n. 15 min",
            "IRREGULAR_DEPARTURES_MAX_30": "Epäsäännölliset vuorovälit, odotus enintään n. 30 min",
            "VENDING_MACHINE_OUT_OF_ORDER": "Maksupääte ei toimi",
            "BICYCLE_STATION_OUT_OF_ORDER": "Pyöräasema pois käytöstä",
            "BICYCLE_SYSTEM_OUT_OF_ORDER": "Koko pyöräjärjestelmä pois käytöstä",
            "REDUCED_BICYCLE_PARK_CAPACITY": "Osa pyöräpaikoista pois käytöstä",
            "OTHER": "Muu vaikutus",
            "NO_TRAFFIC_IMPACT": "Ei liikennevaikutusta",
            "UNKNOWN": "Tuntematon vaikutus"
        }
"type" : {
            "CANCEL_DEPARTURE" : "Lähtö peruttu",
            "SKIPPED_STOP_CALLS" : "Pysäkkejä jäänyt väliin",
            "EARLY_DEPARTURE" : "Lähtenyt lähtöpysäkiltä etuajassa",
            "LATE_DEPARTURE" : "Lähtenyt myöhässä",
            "DEPARTURED_AFTER_NEXT_JOURNEY" : "Lähtenyt seuraavan aikataulunmukaisen lähdön jälkeen",
            "BLOCK_FIRST_DEPARTURE_LATE" : "Ketjun ensimmäinen lähtö lähtenyt myöhässä",
            "EARLY_DEPARTURE_FROM_TIMING_POINT" : "Lähtenyt ajantasauspysäkiltä etuajassa",
            "TIS_ERROR" : "LIJ-vika tai käyttövirhe",
            "DETOUR" : "Poikkeusreitti",
            "CLOSED_STOP" : "Pysäkki suljettu"
        }
"deviationpartials": {"end": "Lähdön lopusta", "middle": "Lähdön keskeltä", "start": "Lähdön alku", "whole": "Koko lähtö"}


"impacts": {
            "DELAYED": "Delayed",
            "POSSIBLY_DELAYED": "Possibly delayed",
            "REDUCED_TRANSPORT": "Reduced transport",
            "CANCELLED": "Cancelled",
            "POSSIBLE_DEVIATIONS": "Possible deviations",
            "RETURNING_TO_NORMAL": "Returning to normal",
            "DISRUPTION_ROUTE": "Diversion route",
            "DEVIATING_SCHEDULE": "Deviating schedule",
            "IRREGULAR_DEPARTURES": "Irregular departures",
            "IRREGULAR_DEPARTURES_MAX_15": "Irregular departures max 15 min",
            "IRREGULAR_DEPARTURES_MAX_30": "Irregular departures max 30 min",
            "VENDING_MACHINE_OUT_OF_ORDER": "Vending machine out of order",
            "BICYCLE_STATION_OUT_OF_ORDER": "Bicycle station out of order",
            "BICYCLE_SYSTEM_OUT_OF_ORDER": "Bicycle system out of order",
            "REDUCED_BICYCLE_PARK_CAPACITY": "Reduced bicycle park capacity",
            "OTHER": "Other impact",
            "NO_TRAFFIC_IMPACT": "No traffic impact",
            "UNKNOWN": "Unknown impact"
        }
"type" : {
            "CANCEL_DEPARTURE" : "Cancel departure",
            "SKIPPED_STOP_CALLS" : "Stops skipped",
            "EARLY_DEPARTURE" : "Start departure early",
            "LATE_DEPARTURE" : "Start departure late",
            "DEPARTURED_AFTER_NEXT_JOURNEY" : "Departured after next journey",
            "BLOCK_FIRST_DEPARTURE_LATE" : "Departured block's first departure late",
            "EARLY_DEPARTURE_FROM_TIMING_POINT" : "Start departure early from timing point",
            "TIS_ERROR" : "TIS error or user error",
            "DETOUR" : "Detour",
            "CLOSED_STOP": "Stop closed"
        }
"deviationpartials": {"end": "End of departure", "middle": "Middle of departure", "start": "Start of departure", "whole": "Whole departure"},

**Comment by danieldunderfelt** [comment]
Thanks, adding them now.
