### ISSUE TITLE
Disruptions in start view

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#391]
This start view should have olla notices and cancellations listed. Highest priority notice up. No there is only 1 and that says "all routes" even though that one has NO route, it is for only 1 stop

![image](https://user-images.githubusercontent.com/39256978/64759290-62473300-d53f-11e9-9114-6e8498e6cd46.png)

**Comment by danieldunderfelt** [comment]
Alerts and cancellations have had multiple fixes and updates, so this should now be resolved.

**Comment by samijuhani** [comment]
Higher priority up before closing. Also could we use "Common numbers" for line and stops, f.ex. 550 and H4353. Also we have same alert twice, it has changed the priority I assume but still there is only 1 alert at one time:

![image](https://user-images.githubusercontent.com/39256978/64952535-43bba180-d889-11e9-8ed3-595f1e452dd8.png)

**Comment by danieldunderfelt** [comment]
For the stop ID's we'd have to query the JORE database separately for each alert to find out the short ID as the alert only has the long stop ID attached. We can do this but it would introduce some amount of lag to most requests. For routes we can parse the line ID without consulting the JORE database.

**Comment by samijuhani** [comment]
No lag at this time

**Comment by danieldunderfelt** [comment]
That's what I thought! The short stop ID could also be added to the alert data by the service that created the alert.

**Comment by danieldunderfelt** [comment]
This should be fixed for now.
