### ISSUE TITLE
Sorting in route search (9=1009, not 1001 9 first), also stop search

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#392]
![image](https://user-images.githubusercontent.com/39256978/64759395-a0445700-d53f-11e9-8d68-9a499ce3e6ed.png)

**Comment by samijuhani** [comment]
Another issue in route search: "1020" gives all routes that have stop including numbers 1020 in start of line. Should not do that, no need to match to stops, only to route number: 1020 always should give route 1020 as top result.

**Comment by samijuhani** [comment]
Works as intended

**Comment by samijuhani** [comment]
No, one new issue from this:
Before I could search stop H2164 with 2164 fine, now search "2164" does not give anything. Should still give H2164.

**Comment by danieldunderfelt** [comment]
Ok, I'll fix it.

**Comment by danieldunderfelt** [comment]
Now fixed in dev and stage!

**Comment by samijuhani** [comment]
Works
