### ISSUE TITLE
"Viikon lähdöt" end up in timeout

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#393]
No matter what line etc

**Comment by danieldunderfelt** [comment]
Looks like the HFP database cannot handle this query. Not sure what to do about this, as the view optimization would probably eat the whole disk in one bite.

**Comment by samijuhani** [comment]
We can hide the feature for starts until we have a solution

**Comment by danieldunderfelt** [comment]
Alright, I'll just return an empty result from that query for now.
