### ISSUE TITLE
Busy stops or full day of busy route search gives network error

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#395]
Time out but F5 shows data instantly. Example H2410, H2407, 550 etc

**Comment by danieldunderfelt** [comment]
Under investigation.

**Comment by samijuhani** [comment]
No errors anymore after timeout changes but more speed would still be welcome. If possible.

**Comment by samijuhani** [comment]
Lets use hfp ve dep events for these as planned, should make it way more quick. Closing when done and tested.

**Comment by danieldunderfelt** [comment]
Fixed with DEP events.

**Comment by samijuhani** [comment]
No network errors since.
