### ISSUE TITLE
Add groups in HSL ID for operator users

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#396]
Finalize groups for domains in hsl id before launch.

oper | Operator name | Domain
-- | -- | --
6 | Oy Pohjolan Liikenne Ab | @ pohjolanliikenne.fi
12 | Helsingin Bussiliikenne Oy | @ kabus.fi
17 | Tammelundin Liikenne Oy | @ tammelundinliikenne.fi
18 | Pohjolan Kaupunkiliikenne Oy | @ pohjolanliikenne.fi
20 | Bus Travel Åbergin Linja Oy | @ aberginlinja.fi
21 | Bus Travel Oy Reissu Ruoti | @ reissuruoti.fi
22 | Nobina Finland Oy | @ nobina.fi
30 | Savonlinja Oy | @ savonlinja.fi
36 | Nurmijärven Linja Oy | @ korsisaari.fi
40 | HKL-Raitioliikenne | @ hel.fi
45 | Transdev Vantaa Oy | @ transdev.fi
47 | Taksikuljetus Oy | @ taksikuljetus.fi
50 | HKL-Metroliikenne | @ hel.fi
51 | Korsisaari Oy | @ korsisaari.fi
54 | V-S Bussipalvelut Oy | @ vsbus.fi
55 | Transdev Helsinki Oy | @ transdev.fi
58 | Koillisen Liikennepalvelut Oy | @ taksikuljetus.fi
59 | Tilausliikenne Nikkanen Oy | @ tilausliikennenikkanen.fi
90 | VR Oy | @ vr.fi

**Comment by danieldunderfelt** [comment]
Added these now. Note that HKL-Metroliikenne and HKL-Raitioliikenne will share groups due to them having the same domain.

**Comment by samijuhani** [comment]
Also 6 & 18, 45 & 55 and 36 % 51 are same company and share rights

**Comment by samijuhani** [comment]
And 47 & 58

**Comment by danieldunderfelt** [comment]
Yes I noticed! The domain will get groups for both operator IDs.

**Comment by samijuhani** [comment]
Admin config:
pohjolanliikenne.fi=operator,op_6,op_18,pohjolanliikenne
kabus.fi=operator,op_12,kabus
tammelundinliikenne.fi=operator,op_17,tammelundinliikenne
aberginlinja.fi=operator,op_20,aberginlinja
reissuruoti.fi=operator,op_21,reissuruoti
nobina.fi=operator,op_22,nobina
savonlinja.fi=operator,op_30,savonlinja
korsisaari.fi=operator,op_36,op_51,korsisaari
hel.fi=operator,op_40,op_50,op_hkl,hel
transdev.fi=operator,op_45,op_55,transdev
taksikuljetus.fi=operator,op_47,op_58,taksikuljetus
vsbus.fi=operator,op_54,vsbus
tilausliikennenikkanen.fi=operator,op_59,tilausliikennenikkanen
vr.fi=operator,op_90,vr
