### ISSUE TITLE
28hr problems is back

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#398]
https://reittiloki.hsl.fi/?route.routeId=&route.direction=0&route.originStopId=&mapView=60.198538674787386%2C24.93821114301682%2C19&mapBaseLayer=Digitransit&stop=1173404&date=2019-09-16

![image](https://user-images.githubusercontent.com/39256978/65013736-ed9c3c00-d924-11e9-91c8-cdb7af1ceb9c.png)

**Comment by danieldunderfelt** [comment]
We should probably not do anything with departures until we get the DEP event_type in the database which tells exactly us when the vehicle departed and will simplify our queries and make them faster. When it arrives I'll make sure that the night journeys are also displayed correctly.

**Comment by samijuhani** [comment]
Fix for #395 should do this.

**Comment by danieldunderfelt** [comment]
To clarify; this SHOULD work, but I am planning to overhaul the departures during work on #396 with the DEP events anyway so that's a good time to fix this as well.

**Comment by danieldunderfelt** [comment]
None of the departures from that stop after midnight seem to have any data. After midnight departures on other stops work fine. Can you confirm that these journeys were actually driven?

**Comment by samijuhani** [comment]
Reproduces also 17.9. and with other tram stops. Need to find out why.

**Comment by samijuhani** [comment]
Also in dev with events.

**Comment by danieldunderfelt** [comment]
I'm not sure what to do about this. The data is not in our HFP database, so the error is at some point before the sink in the pipeline.

**Comment by samijuhani** [comment]
I'll investigate

**Comment by samijuhani** [comment]
So problem was that the tram stops tested had (systemwise)-unplanned disruption route on those stops. Not a bug at this stage, only missing alerts is something we should have had and told user this. Fixing that in another issue, closing this.
