### ISSUE TITLE
Translation fix

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#402]
![image](https://user-images.githubusercontent.com/39256978/65216376-50bed780-dab9-11e9-8f2b-a3893be9f7fc.png)

**Comment by samijuhani** [comment]
area search in english

**Comment by samijuhani** [comment]
Same in sv lang

**Comment by danieldunderfelt** [comment]
This is now fixed in dev. I also made sure all translations are found in all languages (swedish events and help texts still in Finnish, but it's not the highest priority).
