### ISSUE TITLE
"No data" even though there are some

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#403]
Maybe we could say something like "partial data" for these cases

![image](https://user-images.githubusercontent.com/39256978/65230397-760e0e80-dad6-11e9-8249-b7706a440aca.png)

**Comment by samijuhani** [comment]
https://reittiloki.hsl.fi/journey/20190919/113600/2510/1/0022_1166?mapView=60.17747663620248%2C24.925231933593754%2C12&route.routeId=2510&route.direction=1&route.originStopId=1431187&vehicle=0022%2F1166&live=false&time=11%3A36%3A00

**Comment by danieldunderfelt** [comment]
This is due to the DEP event missing from the first stop, which is what we query for when loading that list. We could try to get more events than DEP with the events query, but the legacy query is already heavy enough so I wouldn't make it fetch more data.

**Comment by danieldunderfelt** [comment]
Now it fetches both DEP and PDE events for the first stop, and the PDE is used when the DEP does not exit. Testable in dev now.

@samijuhani do we need to shoe the user that we are falling back on the PDE event or is that not necessary?
