### ISSUE TITLE
Legacy events bugs

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#405]
1. Journey list empy
2. Additional arrivals after departure

![image](https://user-images.githubusercontent.com/39256978/65421721-1e8cdd00-de0d-11e9-8827-d92baa9e9c96.png)

**Comment by danieldunderfelt** [comment]
This was probably a cache thing, I cleared the cache and it seems works now. Let's keep an eye on it through the day.
