### ISSUE TITLE
Use PDE events for normal departures

### ISSUE THREAD

**Issue by danieldunderfelt** [HSLdevcom/transitlog-ui#410]
For normal departures the main departure event should be PDE  instead of DEP.

A normal departure is a departure that is not from the origin stop or from a time adjustment stop.

**Comment by samijuhani** [comment]
Seems fine, though "passed" could use some work as there are 3 departure events. Should show only  that is "Ajoi pysäkin ohi pysähtymättä"

![image](https://user-images.githubusercontent.com/39256978/65763473-2fe72980-e12c-11e9-8403-6d9492d397de.png)

**Comment by danieldunderfelt** [comment]
I wouldn't filter out any events that the user has chosen to see. Also, wasn't the app supposed to show all events? The PAS event is one of them, among other stop-related events.

**Comment by samijuhani** [comment]
True question could be why there are multiple events sent fron vehicle in this case.

**Comment by danieldunderfelt** [comment]
Yes. I think the app should show all events that exist and the user can filter out the ones they don't want to see.
