### ISSUE TITLE
Make admin banner a bit more stand out by using a different color

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#418]
User suggested using different color to make bar more noticeable.

**Comment by danieldunderfelt** [comment]
How much do we want the admin bar to stand out? I designed it to not stand out, so that it wouldn't be in the way.

**Comment by danieldunderfelt** [comment]
How about this:

![Screenshot from 2019-10-07 06-56-01](https://user-images.githubusercontent.com/3145668/66284238-9b20c080-e8cf-11e9-9856-83794e16a419.png)

**Comment by samijuhani** [comment]
Haha stands out better if not using dark mode like me :) Fine at is for now.
