### ISSUE TITLE
Aerial map

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#42]
Aerial map should be possible to use also with general map. User should be able to easily toggle between map types.

Easiest solution is to wait for digitransit map to have this feature but timetable for that is not known.

**Comment by danieldunderfelt** [comment]
PR #59 brings aerial map support. I looked at how OMM has done it, but the OMM aerial map doesn't include roads so I integrated Google Maps as a baselayer in Leaflet. The hybrid map is perfect, as the aerial images themselves are clear and it also includes roads and other map stuff. Do tell if there is some reason why we couldn't use Google Maps.

**Comment by danieldunderfelt** [comment]
Okay, good to know. If cost is an issue and the aerial map is required, we should find the cheapest. A free solution doesn't exist afaik. Or if the OMM aerial map is sufficient, I can integrate that one, but the hybrid map from Google is definitely superior.

**Comment by samijuhani** [comment]
OMM map is good for us and does not cost any extra.

**Comment by tuukka** [comment]
For a hybrid map, you could make a partly-translucent variant of the HSL map style and layer on top of the HSY aerial photos

**Comment by danieldunderfelt** [comment]
@tuukka hah that's an interesting idea!

@samijuhani Ok, I will give the OMM map another look.

**Comment by samijuhani** [comment]
Oh and point was OMM aerial maps are our/HSY maps that we photograph ourselves.

**Comment by danieldunderfelt** [comment]
Okay now I'm confused, as I was told HSY won't let us use their maps. But I'll copy the OMM implementation if we are allowed to use it after all.
