### ISSUE TITLE
Date on url does not change when changing date in ui

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#425]

**Comment by samijuhani** [comment]
Correction: Date changes but problem is that getting the data for the journey takes too long (minutes) after date change and url updates only when data has been fetched.

**Comment by danieldunderfelt** [comment]
I am observing the opposite behaviour: when a journey is selected and I change the date, the url will update first and then the data is loaded. So I'm afraid I can't reproduce this issue.

**Comment by samijuhani** [comment]
True, tried to reproduce and works as you said. Can't remember the original way to reproduce anymore so closing.
