### ISSUE TITLE
Update-button does not update lists reliably

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#426]
Most of the times journey, stop lists are not updating when pressing update when looking at data that updates after original search.

**Comment by danieldunderfelt** [comment]
This could be a cache thing. Will investigate when the data is flowing again.

**Comment by danieldunderfelt** [comment]
Added a skip-cache feature to the server so the UI can tell the server to skip the cache. This header is now sent for the route departures and stop departures requests when the user clicks "Update".

I also confirmed that the Update button works as designed without this feature, but the results would come directly from the cache giving the impression that the update didn't work.

This is now in dev.

**Comment by samijuhani** [comment]
Works
