### ISSUE TITLE
Alert validities are not updated correctly 

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#427]
For example 90R alert has been cut short but is still visible today. Should not be.

![image](https://user-images.githubusercontent.com/39256978/66186869-185bf380-e68c-11e9-8742-a1a7bad6110f.png)

**Comment by danieldunderfelt** [comment]
Sinkissä ei taida olla päivitys-logiikkaa. Jos tulee toinen alert samalla ID:llä kun mitä on jo kannassa, se uusi ei kirjoiteta.

@hellej voisi katsoa tämän ehtiessä, alert-sinkillä ei pitäisi olla niin paljon työtä ettei se voisi päivittää alertteja insertin aikana. Tai sitten vaan poistaa vanha ja kirjoittaa uusi sen sijaan.

**Comment by samijuhani** [comment]
@hellej remember this at some point.

**Comment by hellej** [comment]
@samijuhani It seems that the alert was created with valid_to date in the past (based on the date of the email in the screenshot). Non-valid alerts are not queried from OMM and hence not archived for transitlog either.

**Comment by hellej** [comment]
A solution: let's add a new alert source specific to transtilog to transitlog-sink stack. It will query both active alerts and all modified alerts (since last query): https://github.com/HSLdevcom/transitdata-omm-alert-source/pull/23

**Comment by danieldunderfelt** [comment]
@hellej is this feature working now? I see that the PR is merged.
