### ISSUE TITLE
Show data for selected journey

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#43]
Ui should show this data for journey:

Lähtöaika
Lopetusaika
Terminaaliaika
Elpymisaika
Kalustovaatimus
Kilpailukohde
HSL Lähtöketju
Operaattorin lähtöketju
Liikennöitsijä
Alihankkijat
Kuljettaja
Nousut
Maksimikuorma
Poikkeamatiedot
Tiedotteet
Säätiedot

Needed: API's to all this.

**Comment by samijuhani** [comment]
These terminal time, recovery time, contract were discussed in planning 1.10. To be added to Jore-poiminta.

**Comment by samijuhani** [comment]
![image](https://user-images.githubusercontent.com/39256978/46342917-c3366d80-c644-11e8-815c-4cc9ba44aff4.png)

**Comment by danieldunderfelt** [comment]
Many items on this list are implemented.
