### ISSUE TITLE
Area search time has 5 cemented to it

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#431]
Can't delete/change that 5

![image](https://user-images.githubusercontent.com/39256978/66455737-45d1e400-ea74-11e9-8e4f-6258cbd45479.png)

**Comment by danieldunderfelt** [comment]
Whoops, I'll sort it out!

**Comment by danieldunderfelt** [comment]
Cannot reproduce, sorry. We need to find out under which circumstances it happens.

**Comment by samijuhani** [comment]
Got it to reproduce like this:
Trying to delete all digits leaves the minimum 5 -> cannot input "60" or anything else as 5 stays

**Comment by danieldunderfelt** [comment]
Sorry, still can't reproduce. Backspace shouldn't be able to remove the 5, and I can't gt it to freeze at 5.

**Comment by danieldunderfelt** [comment]
I attempted to fix it, let me know if it happens again.

**Comment by samijuhani** [comment]
Yes the problem is that user expects backspace to work. 

https://drive.google.com/file/d/1BiJsOh7vgiyMi09wo_M9EwjLQWLbTHZR/view

**Comment by danieldunderfelt** [comment]
Oooh okay, I get it now. I'll see what I can do.

**Comment by danieldunderfelt** [comment]
This is now fixed. Will appear in dev at some point.

**Comment by samijuhani** [comment]
Works in stage
