### ISSUE TITLE
Bring back "Show all vehicles from route after route search"

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#432]
Should see vehicle icon in the map from searched route here but nothing

![image](https://user-images.githubusercontent.com/39256978/66456215-ad3c6380-ea75-11e9-9e92-ece0894d839c.png)

**Comment by danieldunderfelt** [comment]
I turned this off temporarily as it was a bit too heavy to load. Not a bug!

**Comment by samijuhani** [comment]
Should we try to bring it back

**Comment by danieldunderfelt** [comment]
We can try, but it'll be slow. I can try to make a materialized view of it too.

**Comment by danieldunderfelt** [comment]
The materialized view works nicely, testable in dev and stage.

**Comment by samijuhani** [comment]
Not seeing this in stage env

**Comment by danieldunderfelt** [comment]
This didn't seem to work after all. Let's wait with it until we have the new tables and try again.

**Comment by danieldunderfelt** [comment]
This feature is now re-enabled in dev and stage! It should be faster than before Citus, but don't expect the vehicles to load instantly. It's still a very heavy query.

**Comment by samijuhani** [comment]
Works
