### ISSUE TITLE
Vehicle search takes very long ang does not give journeys even signed in

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#435]
https://reittiloki.hsl.fi/?mapView=60.188097233013956%2C24.93896484375%2C13&vehicle=0040%2F410&time=07%3A48%3A16

![image](https://user-images.githubusercontent.com/39256978/66553857-97ea3680-eb54-11e9-8198-2ae4435c7fe6.png)

**Comment by danieldunderfelt** [comment]
That tram doesn't have any journeys on this day. It does take a while for it to figure this out, which isn't good, but I also don't want to cache empty results. It takes longer for it to try and find results that don't exist than to find results that do exist. We can try to optimize this, but as far as I can see it works correctly for now.

**Comment by danieldunderfelt** [comment]
I updated the "no results" message for logged in users to better eflect that there are no results or that the account may not be authorized to see them.

**Comment by danieldunderfelt** [comment]
I'll try to make a materialized view of the unsigned events. It it works, it'll speed it up immensely.

**Comment by samijuhani** [comment]
Did comparisons with same vehicle, when deadruns are drawed to map:
Stage 5 sec
Prod 1 min 33 sec

wow

**Comment by samijuhani** [comment]
Today the speed enhancements are not there anymore in stage. Vehicle dead run search again takes minutes as in prod.

**Comment by danieldunderfelt** [comment]
It should still be pretty quick, all the vehicles I tested didn't take long to fetch. Anyway, this will be solved with the new table schema so I'll put this on the backlog for now.

**Comment by danieldunderfelt** [comment]
This should be fixed now.
