### ISSUE TITLE
Date missing from the url when searching a vehicle

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#439]
![image](https://user-images.githubusercontent.com/39256978/66626002-41860200-ebff-11e9-9560-495e2a9efc4d.png)

**Comment by samijuhani** [comment]
Still no date in url after vehicle search if user has not changed the date

**Comment by samijuhani** [comment]
To be exact, seems to be missing at least when user has pressed "Palauta asetukset"

**Comment by danieldunderfelt** [comment]
Right, reset does reset everything. Special case for date added to keep it in the URL.

**Comment by samijuhani** [comment]
Yes works in stage
