### ISSUE TITLE
Back-end needs

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#44]

**Comment by varpushaukka** [comment]
### Get hfp-data by bbox
if we don't know the bus or route, but only an area like #10

**Comment by danieldunderfelt** [comment]
Data cropping server-side. IE "take every nth item/second".

**Comment by varpushaukka** [comment]
get hfp data by vehicle id and date/timescale (lähtöketju)

**Comment by danieldunderfelt** [comment]
Could we add `received_at_unix` and `journey_start_timestamp` props to the hfp data?
