### ISSUE TITLE
Empty result when using veekly departures today 14.10.

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#441]
Works for last week after changing dates

https://reittiloki.hsl.fi/journey/20191014/080500/2550/1/0012_1317?live=false&date=2019-10-14&time=08%3A05%3A00&route.routeId=2550&route.direction=1&route.originStopId=1453287&mapView=60.20971903781771%2C25.07732391357422%2C12&vehicle=0012%2F1317&tab=journeys_by_week

![image](https://user-images.githubusercontent.com/39256978/66731263-244f6e80-ee5f-11e9-8f3b-90279a7067b6.png)

**Comment by danieldunderfelt** [comment]
Can reproduce, will fix soon!

**Comment by danieldunderfelt** [comment]
Sorry, can't reproduce this anymore. Maybe it only happens on mondays?

**Comment by samijuhani** [comment]
Just reproduced it first time trying https://reittiloki.hsl.fi/?mapView=60.20792798365617%2C24.78652954101563%2C11&route.routeId=2550&route.direction=1&route.originStopId=1453287&tab=journeys_by_week&date=2019-10-16

**Comment by danieldunderfelt** [comment]
Ok, I'll try again.

**Comment by danieldunderfelt** [comment]
This is now fixed and should work soon in dev and stage.

**Comment by samijuhani** [comment]
Works in stage env
