### ISSUE TITLE
STAGE: Not finding journey from block view

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#446]
https://stage.reittiloki.hsl.fi/journey/20191016/252900/1096N/1/0017_43?mapView=60.202810147156775%2C25.05912780761719%2C12&stop=&date=2019-10-16&vehicle=0017%2F43&route.routeId=1096N&route.direction=1&route.originStopId=1020122&live=false&time=25%3A29%3A00&tab=vehicle-journeys

Works in prod at the moment

**Comment by samijuhani** [comment]
![image](https://user-images.githubusercontent.com/39256978/66996515-8b785780-f0d9-11e9-88f3-477665ce656b.png)

**Comment by samijuhani** [comment]
PROD:

![image](https://user-images.githubusercontent.com/39256978/66996756-f3c73900-f0d9-11e9-8e4a-ba7a99a92550.png)

**Comment by samijuhani** [comment]
For some reason this other journey is not selectable at times already, stage
![image](https://user-images.githubusercontent.com/39256978/67003600-0005c300-f0e7-11e9-86c8-8dfa8ef0845a.png)

**Comment by danieldunderfelt** [comment]
This was a cache issue where processed unsigned events were being cached instead of raw events. Fixed now!

**Comment by samijuhani** [comment]
Got the same result from opening link from bug description 
![image](https://user-images.githubusercontent.com/39256978/67181770-40ff1f80-f3e6-11e9-962d-145792391140.png)

**Comment by danieldunderfelt** [comment]
Okay, seeing the issue. Some problems with 24h+ departures. Fixing!

**Comment by danieldunderfelt** [comment]
This is now fixed. Will soon arrive in dev and stage!
