### ISSUE TITLE
2510/2 says "Ei lähtöjä" today for no reason

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#457]
Huomasin, että linjan 2510 2-suunnan tietoja ei olisi tältä päivältä olemassa transitlogin mukaan. Kun valitsee yksittäisen lähdön niin saa silti tiedot eli ne on olemassa vaikka tuolla lukee " Ei tietoja".

https://reittiloki.hsl.fi/journey/20191022/050300/2510/2/0022_1145?route.routeId=2510&route.direction=2&route.originStopId=2231225&mapView=60.183516955515096%2C24.835281372070316%2C12&date=2019-10-22&journeyDetailsOpen=false&live=false&time=05%3A03%3A00&vehicle=0022%2F1145

**Comment by danieldunderfelt** [comment]
Cache problem, fixed now. The list was probably being fetched when the HFP database was down and the empty list got stuck in cache. I'll make sure empty lists are not cached.

**Comment by danieldunderfelt** [comment]
Also, a feature that is not yet in prod will refresh the cache for each query when the Refresh button is used so this should be user solvable with the button when we get new stuff into production.

**Comment by samijuhani** [comment]
Works, thanks.
