### ISSUE TITLE
"Ei tietoja" even though departure event is there

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#460]
https://stage.reittiloki.hsl.fi/journey/20191015/051400/4560/1/0012_1510?date=2019-10-15&live=false&time=05%3A14%3A00&vehicle=0012%2F1510&mapView=60.20262027786674%2C25.153970718383793&mapZoom=14&route.routeId=4560&route.direction=1&route.originStopId=1541193

PROD works fine with this journey

**Comment by danieldunderfelt** [comment]
Hmm okay, a weird bug where the stops are in the wrong order. It also depends on the environment as the same code works with prod data. So there's a bug if the data is somehow wrong. Good catch, I'll fix it!

**Comment by danieldunderfelt** [comment]
Fixed now! The data is missing in stage from before Mellunmäki though, but now it is displayed correctly.
