### ISSUE TITLE
Suggested: Graph view  about departures (first) and arrivals (last)

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#469]
Operators suggested, inspired of weekly view, that a graph about same info with larger scale of data would be useful.

tbd: More specs about the view from users

**Comment by samijuhani** [comment]
Needs planning and discussion with users of actual need.

**Comment by MinnaEmilia** [comment]
Based on the evaluation of the need, this feature will not be implemented at this point. --> let's close the ticket.
