### ISSUE TITLE
Different departure times in different views

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#470]
https://reittiloki.hsl.fi/journey/20191031/051100/1039/2/0012_1838?date=2019-10-31&route.routeId=1039&route.direction=2&route.originStopId=4150263&vehicle=0012%2F1838&live=false&mapView=60.26113087943083%2C24.856427907943726&time=05%3A11%3A11&mapZoom=18&mapOverlays=Stopped+vehicle%2CStop+radius&tab=vehicle-journeys

![image](https://user-images.githubusercontent.com/39256978/67943630-192c6a80-fbe3-11e9-8867-22c99a707854.png)

**Comment by danieldunderfelt** [comment]
This journey has two DEP events from Myyrmäen Asema, and due to deduplication, the departure list selected the last one while the events list and the vehicle departure list selected the first one. I'll ensure that all views show the same event if there are many. The events list could also show both DEP events.

**Comment by danieldunderfelt** [comment]
All events, also duplicates, visible in the event log:
![Screenshot from 2019-11-01 07-09-01](https://user-images.githubusercontent.com/3145668/68003568-9b19a380-fc76-11e9-923e-8e47e823feba.png)

Is this OK?

**Comment by samijuhani** [comment]
There was a mistake of departing the stop twice by driver. Seems fine like this.

**Comment by danieldunderfelt** [comment]
Ok! And I assume the later time is the "correct" one?

**Comment by samijuhani** [comment]
Later 1 is the correct one but at the moment OMM sees only the first and users will come to reittiloki to see the problem with the first "too early" time. Need to show that also. I'd say we use it for now as the master to see the problems in usage. Change this later if needed.

**Comment by danieldunderfelt** [comment]
Got it. At least it is now visible in Reittiloki that there are many events.

**Comment by samijuhani** [comment]
Good
