### ISSUE TITLE
Wrong days dead run shown in the map

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#472]
Should only show 30.10. 4:30-31.10. 4:30 but shows 31.10. 6:00 there:

![image](https://user-images.githubusercontent.com/39256978/68023678-91ad2d00-fcb0-11e9-897d-d97b9558e071.png)

https://reittiloki.hsl.fi/?date=2019-10-30&route.routeId=&route.direction=0&route.originStopId=&live=false&mapZoom=12&time=16%3A48%3A44&mapView=60.35345104264474%2C25.124015808105472&vehicle=0047%2F17

**Comment by samijuhani** [comment]
Still there in stage

**Comment by danieldunderfelt** [comment]
The time range might be a bit greedy, but I'd rather have that than some events being left outside for journeys that are late (for example). Is it a big problem if the deadruns are fetched with the same greedy time range and some events from the next day are shown?

The linked date obviously doesn't have events anymore in Reittiloki, but if it's a problem and you find more of these I'll have a look.

**Comment by samijuhani** [comment]
Let's scrap this for now as it is very uncommon case anyway
