### ISSUE TITLE
Left ahead of time but still green

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#474]
https://reittiloki.hsl.fi/journey/20191101/104600/1075/1/0012_1525?date=2019-11-01&route.routeId=1075&route.direction=1&route.originStopId=1020117&live=false&time=10%3A46%3A08&mapZoom=18&mapView=60.17112637962439%2C24.94381427764893&vehicle=0012%2F1525&mapOverlays=Stopped+vehicle%2CStop+radius&time_increment=2&mapBaseLayer=Aerial

![image](https://user-images.githubusercontent.com/39256978/68123308-3def4d80-ff15-11e9-8703-6cf0087c61c4.png)

**Comment by danieldunderfelt** [comment]
Looks like it left the stop area 8 seconds after the departure time, which is OK. Is there something I'm missing or not understanding?

**Comment by samijuhani** [comment]
The actual departure from stop is earlier. Must be data issue then?

![image](https://user-images.githubusercontent.com/39256978/68183422-1c3da700-ffa5-11e9-8bb1-9a898e65f780.png)

**Comment by samijuhani** [comment]
Can it be that stop radius is changed afterwards in this case?

**Comment by danieldunderfelt** [comment]
It can be that, yes. We are using the DEP event for this, so the departure time here is whatever the timestamp of the DEP event is.
