### ISSUE TITLE
Double data

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#476]
This case clearly has double data for one journey. There is no possibility to see that second data right now. Should be. Does not split to double in journeys table at all, only this stop timetable view.

![image](https://user-images.githubusercontent.com/39256978/68272260-c54ed500-006b-11ea-810d-793f80820a27.png)

https://reittiloki.hsl.fi/journey/20191016/114900/4611/2/0030_15?date=2019-10-16&route.routeId=4611&route.direction=2&route.originStopId=4610247&mapView=60.27208897887721%2C24.99217987060547&mapZoom=12&vehicle=0030%2F15&live=false&time=11%3A13%3A42&tab=timetables&weeklyObservedTimes=arrival&stop=1401104&timetableFilters.route.pending=611&timetableFilters.route.current=611&timetableFilters.minHour.current=&timetableFilters.maxHour.current=

**Comment by danieldunderfelt** [comment]
I got this working by splitting the departures into instances. This doesn't work in the route departure list because one of the journeys doesn't have a DEP event from the first stop, resulting in the departure list not seeing it.

Soon in dev.
