### ISSUE TITLE
Line 7 extra (old) stops

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#478]
https://reittiloki.hsl.fi/?mapView=60.19678166961105%2C24.94729042053223&date=2019-11-05&mapZoom=15&route.routeId=1007&route.direction=1&route.originStopId=1203418&stop=1171407&mapOverlays=Stopped+vehicle%2CStop+radius&tab=journeys&weeklyObservedTimes=arrival

![image](https://user-images.githubusercontent.com/39256978/68672183-bd0a0480-0559-11ea-9348-54e6b70ac899.png)

**Comment by danieldunderfelt** [comment]
This is again a symptom of the history database where we can't delete anything. These extra stops are perfectly valid according to JORE and date range validation, but the length of the route has changed leaving these stops behind.

Luckily, routes have `destinationstop_id`, so we can easily remove any stops that have a `stop_index` larger than the stop where the `stop_id` matches the `destinationstop_id` of the route. I have added this validation to the existing validation for route stops. Testable in dev!
