### ISSUE TITLE
Arrival to last stop missing in weekly view if not stopped to last stop

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#479]
Add ARR event as arrival time when this is the case.

https://reittiloki.hsl.fi/journey/20191106/162500/1097/2/0022_783?mapView=60.2107437859826%2C25.07865965366364&date=2019-11-06&live=false&time=16%3A42%3A15&time_increment=1&mapZoom=18&areaEventsRouteFilter=1092&areaEventsStyle=markers&route.routeId=1097&route.direction=2&route.originStopId=1472102&vehicle=0022%2F783&mapBaseLayer=Digitransit&mapOverlays=Stop+radius%2CStopped+vehicle&tab=journeys_by_week&weeklyObservedTimes=arrival

![image](https://user-images.githubusercontent.com/39256978/68737771-24bd5f80-05ed-11ea-86b4-bd8be996be0b.png)

**Comment by danieldunderfelt** [comment]
Yes, using PDE and ARR events instead of DEP and ARS events has been planned for a while. I wouldn't call it a bug...

I'll get working on it.

**Comment by danieldunderfelt** [comment]
This is now in dev. Related to issue #403. Do we need to mark the arrivals which use the fallback event?

**Comment by samijuhani** [comment]
Yeah would be useful to see that time is triggered differently than usual.

**Comment by samijuhani** [comment]
Not seeing arrival time in dev still for this https://dev.reittiloki.hsl.fi/journey/20191106/162500/1097/2/0022_783?mapView=60.2103373552357%2C25.0777530670166&date=2019-11-06&live=false&time=16%3A42%3A15&time_increment=1&mapZoom=14&areaEventsRouteFilter=1092&areaEventsStyle=markers&route.routeId=1097&route.direction=2&route.originStopId=1472102&vehicle=0022%2F783&mapBaseLayer=Digitransit&mapOverlays=Stop+radius%2CStopped+vehicle&tab=journeys_by_week&weeklyObservedTimes=arrival&details-tab=journey-events

**Comment by danieldunderfelt** [comment]
I have added the event types to the event list of journeys, but we can also show a small asterisk or something for ARR and PDE events used here.

**Comment by danieldunderfelt** [comment]
For those departures that still don't have an arrival time, it is likely that neither the ARR or ARS event was found. Check the health report of the journey, if it says that the arrival event was derived from vehicle positions, none of the listings will show the event. Virtual events can only be created when all vehicle positions for a journey are fetched, and that would be way too slow for any view that shows more than one departure.

![Screenshot from 2019-11-14 14-24-08](https://user-images.githubusercontent.com/3145668/68857128-d55d5900-06ea-11ea-92eb-c8781aee1dbf.png)

This is how the health report reports arrival events that were derived from vehicle positions.

**Comment by danieldunderfelt** [comment]
This is now also in stage so you can do further testing there.

**Comment by samijuhani** [comment]
https://dev.reittiloki.hsl.fi/journey/20191106/162500/1097/2/0022_783?mapView=60.21005012463372%2C25.07824122971215&date=2019-11-06&live=false&time=16%3A42%3A16&time_increment=1&mapZoom=18&areaEventsRouteFilter=1092&areaEventsStyle=markers&route.routeId=1097&route.direction=2&route.originStopId=1472102&vehicle=0022%2F783&mapBaseLayer=Digitransit&mapOverlays=Stop+radius%2CStopped+vehicle&tab=journeys_by_week&weeklyObservedTimes=arrival&details-tab=journey-events this same is still missing arrival time. Use ARR event if needed.

**Comment by danieldunderfelt** [comment]
Ok, found the issue. Fixed now in dev and stage.

**Comment by samijuhani** [comment]
Works on that journey now. But when clicking a journey that has no arrival time loads forever. Regression or another issue? https://dev.reittiloki.hsl.fi/journey/20191105/154500/1097/2/?mapView=60.2242570719367%2C25.093202590942383&date=2019-11-05&live=false&time=15%3A45%3A00&time_increment=1&mapZoom=14&areaEventsRouteFilter=1092&areaEventsStyle=markers&route.routeId=1097&route.direction=2&route.originStopId=1472102&vehicle=&mapBaseLayer=Digitransit&mapOverlays=Stop+radius%2CStopped+vehicle&tab=journeys_by_week&weeklyObservedTimes=arrival&details-tab=journey-events

**Comment by samijuhani** [comment]
Forever = like 5 minutes

**Comment by samijuhani** [comment]
Oh the original journey is not showing any data now, only arrival time

![image](https://user-images.githubusercontent.com/39256978/69123254-8d06b800-0aa9-11ea-8f8f-8cab21be99cb.png)

**Comment by danieldunderfelt** [comment]
The forever load is probably caused my the new tables that are in use in dev. Test this feature in stage!

**Comment by samijuhani** [comment]
Stage does not load forever indeed
