### ISSUE TITLE
Stops in wrong order in DEV

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#481]
![image](https://user-images.githubusercontent.com/39256978/68835901-cca45d00-06c1-11ea-8dab-49ec727e2275.png)

https://dev.reittiloki.hsl.fi/journey/20191114/081500/2550/1/0012_1321?date=2019-11-14&mapView=60.17733170639588%2C24.788331985473636&route.routeId=2550&route.direction=1&route.originStopId=1453287&tab=&details-tab=journey-events&mapZoom=16&vehicle=0012%2F1321&live=false&time=09%3A30%3A00

**Comment by danieldunderfelt** [comment]
The events are ordered accoding to the recorded time, so planned stops with no HFP events may go out of order. Events are now sorted first by the planned time and then by the recorded time which fixes the problem. Soon visible in dev.

But be aware that events which have no planned times (eg. all other than stop events) are still ordered by the recorded time, so some of the other events may be in a different order than anticipated. For example, a stop departure that is not presented as a stop event (for example a DEP for a normal stop) may be in the list before the arrival stop event. If more adjustments to the order are requested I would need a list of all events (including the planned departures) and their exact order relative to each other.

**Comment by samijuhani** [comment]
Good should be enough

**Comment by danieldunderfelt** [comment]
This is now fixed and testable in dev and stage.
