### ISSUE TITLE
Login still does not work after a while

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#483]
When continuing work after lunch, login is not active anymore. F5 shows it that user is not really signed in anymore.

![image](https://user-images.githubusercontent.com/39256978/68939800-284a1580-07aa-11ea-8695-445231077f14.png)

**Comment by samijuhani** [comment]
Now the same, less than 2 hours after logging in again.

**Comment by danieldunderfelt** [comment]
I adjusted the maxAge of the session cookie and now the login is persisted. It should last for at least a month, as the time is reset each time you access the site. Testable in dev and stage.

**Comment by samijuhani** [comment]
Seems to work BUT after I rebooted my computer and reopened the browser, UI did not notice the login (showed as not logged in) but after F5 I was again logged in. Note did not login again, fix itself seems to work but this ui still to look at?

**Comment by danieldunderfelt** [comment]
That seems like a temporary error in fetching the user data from the server. How long did you wait until you pressed F5? Sometimes there's a lag in fetching the user data if the UI has a lot of other things to load simultaneously.

**Comment by samijuhani** [comment]
It was long enough. This morning opening stage fresh I was already logged in so that worked as planned, let's close for now.
