### ISSUE TITLE
Strange behaviour on stage, missing events list and data in the map

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#484]
![image](https://user-images.githubusercontent.com/39256978/69139086-8176b980-0ac8-11ea-95c0-e5df92a40a9b.png)

https://stage.reittiloki.hsl.fi/journey/20191031/054400/4560/1/0012_1517?date=2019-10-31&mapView=60.232141578515225%2C24.981708526611328&vehicle=0012%2F1517&tab=journeys&route.routeId=4560&route.direction=1&route.originStopId=1541193&live=false&details-tab=journey-events&time=05%3A44%3A00&mapZoom=12

**Comment by samijuhani** [comment]
Also some journey pick wrong vehicle (tram in this case)

![image](https://user-images.githubusercontent.com/39256978/69139936-378ed300-0aca-11ea-8174-841f328472d1.png)

https://stage.reittiloki.hsl.fi/journey/20191031/053400/4560/1/0012_1520?date=2019-10-31&mapView=60.20708037085181%2C25.02548217773438&vehicle=0040%2F79&tab=journeys&route.routeId=4560&route.direction=1&route.originStopId=1541193&live=false&details-tab=journey-events&time=05%3A34%3A00&mapZoom=11

**Comment by danieldunderfelt** [comment]
The first problem is fixed.

But I have absolutely no idea how you managed to make the second screenshot happen outside of Photoshop. The header of the journey sidebar looks correct, but the vehicle data is a tram, and the first event is from a stop that does not belong to the 4560 route. The last route that the tram operated was 1001H4/1 which starts with that stop, but that journey happened at 21:18.

This does not happen by entering those selections manually or by clicking the link, so I cannot reproduce it. Do you know the steps you took to arrive at that view?

**Comment by samijuhani** [comment]
No idea anymore. Seems to work, closing.
