### ISSUE TITLE
No stops loaded to journey when selected

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#487]
Does not reproduce when opening the link. F5 fixes.

![image](https://user-images.githubusercontent.com/39256978/69317224-23221600-0c43-11ea-9b59-c111ba0cb209.png)

https://reittiloki.hsl.fi/journey/20191121/085500/4615/1/?date=2019-11-21&mapView=60.17106142205418%2C24.94308471679688&route.routeId=4615&route.direction=1&route.originStopId=1020119&tab=&details-tab=journey-events&mapZoom=12&live=false&time=08%3A55%3A00&vehicle=

**Comment by danieldunderfelt** [comment]
It's really hard to know what causes this if refreshing the app solves it. Sounds like a temporary connection problem.

**Comment by samijuhani** [comment]
Happened again, no cancellations involved.

Steps

1. Search and choose route 1069/1
2. Switch date to tomorrow and back to today

![image](https://user-images.githubusercontent.com/39256978/69320111-3801a800-0c49-11ea-8cb0-8bf1e8d9587e.png)

**Comment by samijuhani** [comment]
Went back to normal after switching date again

**Comment by danieldunderfelt** [comment]
Yes, a reproduction is always useful, tahnks. I'll investigate!

**Comment by danieldunderfelt** [comment]
Got it fixed, testable in stage!

**Comment by samijuhani** [comment]
Could not reproduce in stage anymore
