### ISSUE TITLE
Stop radius not changing in Reittiloki after changing it in Jore

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#488]
This stops radius was enlargened two days ago, still no change in Reittiloki. Are daily data updates working?

1353117

https://reittiloki.hsl.fi/journey/20191118/195600/1064/2/0018_291?mapView=60.250690653876674%2C24.96127545833588&date=2019-11-18&route.routeId=1064&route.direction=2&route.originStopId=1353117&tab=timetables&details-tab=journey-events&mapZoom=18&vehicle=0018%2F291&live=false&time=19%3A56%3A25&mapOverlays=Stopped+vehicle%2CStop+radius&stop=1353117

**Comment by danieldunderfelt** [comment]
Not a bug. Stops have no date_start and date_end validity periods so they are hard to update in our history database. Essentially, if the stop_id already exists the stop won't be imported.

We could develop something for this but it hasn't been done yet.

**Comment by samijuhani** [comment]
So we need just to update the data per latest import always. Could pe position, name, radius for example

**Comment by danieldunderfelt** [comment]
Actually, the import does seem to have stalled. Probably because of the JORE errors reported by Juuso. The update logic seems to be working as intended in the importer. I misremembered the handling for existing stops in this case, they should be updated.

**Comment by danieldunderfelt** [comment]
Yes indeed, the importer reports that the stop name is null when it shouldn't be. I'll make it nullable and restart the importer.

**Comment by danieldunderfelt** [comment]
I made the fields nullable and a new improt is currently running. Let's see if it updates the stops properly.

**Comment by samijuhani** [comment]
Still old radius. I think I saw the bigger radius to flash first but not sure

**Comment by samijuhani** [comment]
What now after opening the link the 3rd time, radius is changed.

**Comment by samijuhani** [comment]
And after F5 it is small (old) again.

**Comment by danieldunderfelt** [comment]
This is certainly interesting, I can confirm the issue. Will try to find a fix!

**Comment by danieldunderfelt** [comment]
I'm guessing that this is a cache problem. Since you are viewing an older day the data is kept in the cache for longer. Also the data is different depending on if you are looking at stops on the map without the route selected (then they are stops) or with a route selected (then they are route segments). This is why the stop radius is different; one shows the new data and one shows older data.

I'll implement better refresh features for this data to fix the problem. Then the data and the cache can be refreshed with the "Update" button.

**Comment by danieldunderfelt** [comment]
Better update functionality implemented. testable in stage, soon in prod.

**Comment by danieldunderfelt** [comment]
The stop radius can now be updated! It should now be correct in the cache for the various queries. If not, just click update.

**Comment by samijuhani** [comment]
Seems to work.
