### ISSUE TITLE
Remove phone number option from registration form

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#489]

**Comment by samijuhani** [comment]
Checking if this is possible

**Comment by danieldunderfelt** [comment]
I had a look in the admin panel and apparently we had a group policy set that required phone number verification. I haven't added this, so maybe it came from an update? I also checked that our namespace and auth client don't require the phone number in any other way. If the issue persists, we need to contact someone who is more knowledgeable about HSL ID.

**Comment by samijuhani** [comment]
Jere will de-select everything else than first name, surnmae and email from form so new accounts are not asked for phone anymore. Let's close this after that is done and tested.

**Comment by samijuhani** [comment]
Deployed to prod and tested to work.
