### ISSUE TITLE
Make journey data coverage to take account missing data from start and stop also

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#490]
1. Recognize missing data from start and end
2. Do not nag about missing data after arriving to last stop
3. Add received_at field to UI and heath check

**Comment by samijuhani** [comment]
Also make it so that this does not say data is missing https://reittiloki.hsl.fi/journey/20191127/053000/2553/1/0022_1060?date=2019-11-27&mapView=60.24478001813164%2C25.01449580769986&route.routeId=2553&route.direction=1&route.originStopId=4940231&tab=journeys&details-tab=journey-health&stop=1385163&vehicle=0022%2F1060&live=false&time=05%3A45%3A32&mapZoom=12

**Comment by samijuhani** [comment]
Also add received_at information to ui and heath check

**Comment by danieldunderfelt** [comment]
This is now upgraded in dev and stage! The received_at timestamp is not yet visible as I didn't find a good place to put it. It's not indicative of bad data health so I don't think it should go in conjunction with this.

**Comment by samijuhani** [comment]
Should we add received_at to here with smaller font after the time row

![image](https://user-images.githubusercontent.com/39256978/69955664-dd98ff00-1506-11ea-81dd-21b65f0688ea.png)

**Comment by samijuhani** [comment]
Also still would like to see from somewhere if there have been delays without checking so close

**Comment by samijuhani** [comment]
? ^

**Comment by danieldunderfelt** [comment]
Oh sorry, I'll still have a look at this. Did you mean delays in the data, ie difference in received_at vs tst?

**Comment by samijuhani** [comment]
Yes and a way to notice about this in health check already so user could see at a glance that data has been delayed in real time.

**Comment by danieldunderfelt** [comment]
This is now in dev and stage. I added a separate delay indicator to the journey panel header, underneath the health indicator. It shows the average delay for all events (VP and others) of the journey. The same average is also visible in the health section.

**Comment by samijuhani** [comment]
I'd say let's remove it from here but leave it to health check page after all. May confuse common user here.

![image](https://user-images.githubusercontent.com/39256978/70210972-aa3fb580-173c-11ea-9eb1-90deaa2def32.png)

**Comment by danieldunderfelt** [comment]
Ok!

**Comment by danieldunderfelt** [comment]
Removed now in dev and stage.

**Comment by samijuhani** [comment]
good
