### ISSUE TITLE
Alert enhancements

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#491]
1. If alert is made for multiple routes, store it to all routes so that all routes can be used in UI. Now is stored only the first/smalles route number
2. Partial cancellations of journeys need to be stored. Daniel be sure to support these when available.

**Comment by samijuhani** [comment]
2:

![image](https://user-images.githubusercontent.com/39256978/69938500-27bdb880-14e6-11ea-9130-16e7fa741728.png)

**Comment by samijuhani** [comment]
1:
![image](https://user-images.githubusercontent.com/39256978/69938766-cc3ffa80-14e6-11ea-8102-95d573577143.png)

**Comment by danieldunderfelt** [comment]
I'll make sure the UI supports these when the data is available.

**Comment by samijuhani** [comment]
Group so that the same alert is only shown once here and tells the routes affected
![image](https://user-images.githubusercontent.com/39256978/70412614-dc635700-1a5d-11ea-9f54-de133e2faace.png)

**Comment by danieldunderfelt** [comment]
Yes, I'm on it!

**Comment by danieldunderfelt** [comment]
The grouping is now visible in dev! Can we depend on the ext_id_bulletin field always being available? It is used for grouping now.

**Comment by samijuhani** [comment]
Grouping of alerts look fine to me. I'll split the cancellations to another issue as it is different thing after all.
