### ISSUE TITLE
Alerts not working

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#492]
There are no alerts shown in ui at all for today, 2.12.. also 1.12., 29.11, 27.11.. and some longer alerts are shown only some days that they are valid.

**Comment by danieldunderfelt** [comment]
Alerts are only shown in the sidebar for the currently selected time. Seems to work for me when I scroll the time slider.

This has been reported as a bug multiple times already, should we just change it to show all alerts for a day if that's more intuitive?

**Comment by samijuhani** [comment]
No, please check this for example this alert. It is valid all hours 26.11.-4.12. Should be visible no matter what time is selected.

![image](https://user-images.githubusercontent.com/39256978/69942860-8a668280-14ed-11ea-9502-dd9c1de0357d.png)

**Comment by danieldunderfelt** [comment]
Ok, I'll investigate!

**Comment by danieldunderfelt** [comment]
Alerts are now fixed in dev and stage. There was a logic error in the query that resulted in some alerts not being fetched properly. Click "update" to refresh the alert list from the database.

**Comment by samijuhani** [comment]
Now I can see the alert in stage in all days EXCEPT 26.11. when it started.

**Comment by danieldunderfelt** [comment]
That's peculiar. I'll check why.

**Comment by danieldunderfelt** [comment]
Now it's working. For some reason I had to add a day to the date with which the alerts are queried to catch the first day.

**Comment by samijuhani** [comment]
Yes seeing the alert in stage now also 26.11.
