### ISSUE TITLE
Live mode does not work

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#493]
https://drive.google.com/file/d/1YK7GCQQu3z4mpbb3EPm8s4M1lVQemBOY/view

**Comment by danieldunderfelt** [comment]
I'm still having trouble viewing the videos, could you describe the issue? I've noticed a data gap in many environments so it may be due to this.

**Comment by danieldunderfelt** [comment]
Fixed now in dev and stage!

**Comment by samijuhani** [comment]
Seems to work in Stage -> prod when possible

**Comment by samijuhani** [comment]
Not working on dev!

**Comment by danieldunderfelt** [comment]
I redeployed dev and now it works. Must have forgotten to do it, sorry!

**Comment by samijuhani** [comment]
Yes works in dev now also
