### ISSUE TITLE
Journey not selected in the left hand journey list after changing date

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#494]
Shouldn't/hasn't it be shown as selected (as it is selected) after changing date. All envs.

![image](https://user-images.githubusercontent.com/39256978/70121947-510e4e00-1678-11ea-8d0b-e41e39bd5be7.png)

**Comment by danieldunderfelt** [comment]
Yes it should. I'll take a look.

**Comment by danieldunderfelt** [comment]
Found the issue, fixed now in dev and stage!

**Comment by samijuhani** [comment]
Tested to work in stage
