### ISSUE TITLE
Add contact info to ui

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#496]
Add contact info infopalvelut@hsl.fi to ui for users to contact us for help, bug reports etc.

**Comment by danieldunderfelt** [comment]
Added now to the right of the admin message bar. Visible in dev and stage.

**Comment by samijuhani** [comment]
Great we'll think about the position still

**Comment by samijuhani** [comment]
New requirement: only show mail info for hsl and operator user that are signed in. Possible?

**Comment by danieldunderfelt** [comment]
Yes it is possible, but it would be visible for all signed in users as the UI doesn't know what groups the user belongs to.

**Comment by samijuhani** [comment]
Damn. Then let's scrap this feature for now.

**Comment by danieldunderfelt** [comment]
We could tell the UI about the groups, but that may lead to authorization logic being duplicated. Now the server performs the logic of what the user is allowed to see, and I don't really want to bring that to the UI. We could ask the server if the user is allowed to see the help email though, but it seems kinda heavy for a small thing like this.

**Comment by samijuhani** [comment]
Nah we'll give the contact info via ITSM and other ways

**Comment by danieldunderfelt** [comment]
So should we remove it for now?

**Comment by samijuhani** [comment]
yes

**Comment by danieldunderfelt** [comment]
Ok, done in dev and stage!
