### ISSUE TITLE
Wrong start time shown in journey view

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#497]
Should be dep (and other views is). For some reason first pde is used here.

![image](https://user-images.githubusercontent.com/39256978/70413053-18e38280-1a5f-11ea-9754-40e0a8959c7f.png)

https://reittiloki.hsl.fi/journey/20191205/145500/4555/2/0018_784?date=2019-12-05&route.routeId=4555&route.direction=2&route.originStopId=4170215&tab=&mapView=60.27717199047997%2C24.853010773658756&details-tab=journey-events&mapZoom=18&vehicle=0018%2F784&live=false&time=14%3A55%3A00

**Comment by samijuhani** [comment]
Does NOT reproduce in DEV or STAGE. Close if something is really done for this

**Comment by danieldunderfelt** [comment]
We decided to use PDE as a fallback if DEP is not available, which it doesn't seem to be. Not sure why the DEP is available in dev and stage, but they do use separate pipelines so the data may vary a little.

**Comment by danieldunderfelt** [comment]
Should we show with a small icon (like the day type) which event it used for the observed time?

**Comment by samijuhani** [comment]
Nah. Please note the the problem is only on 1 view in prod also. So the correct event must be there.

**Comment by danieldunderfelt** [comment]
When I select the journey, the health report says that the DEP event was created from vehicle positions, ie it is virtual. So a DEP eent will be visible in the event list but it is not actually real.
