### ISSUE TITLE
Can't reselect journey from stop timetables view

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#498]
Can't reselect journey after changing it. Also skipping to route view here is unnecessary.

**Comment by samijuhani** [comment]
https://drive.google.com/file/d/14f_1XeCg7N_sPfAcMU0PK5OtfG7i7a9K/view

**Comment by danieldunderfelt** [comment]
Ok, fixed in dev and stage!

**Comment by samijuhani** [comment]
Could not reproduce in dev
