### ISSUE TITLE
Search journey from OMM (url)

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#5]
User gets notification in OMM about deviation in a journey. User clicks "show in transitlog".  Url takes it to given journey in transitlog. OMM can be any app.

Edit:
Needed part for the start of url should be:

/journey/20180606/0806/2224/1/ | /date/time/routeid/direction 

Where 24hr clock is used. Time is actual time of when happened, not 30hr transport day or operating day.

Segments added after that (if any) for exact place/time of jouney after that.

Screenshot from OMM ui below.

![url user story](https://user-images.githubusercontent.com/39256978/41033896-a918b9fa-6990-11e8-931a-1fe128db6940.JPG)

**Comment by haphut** [comment]
What about doubled DatedVehicleJourneys? Should the URL contain the ordinal number of the vehicle, usually `1` or `2`?

I would combine `line number/variant` into the six-character `jore_route_id`.

So the template for the URL would look something like this:
```
<host>/journey/<operating_date>/<jore_route_id>/<direction>/<30_hour_start_time>/<vehicle_ordinal_number>
```
with an unrealistic example like this:
```
https://dev-transitlog-ui.hsldev.com/journey/20180606/3001U/1/2516/2
```

**Comment by samijuhani** [comment]
Great.

**Comment by samijuhani** [comment]
Also to be added: time, vehicle selection, state so that user can send a link of what one is looking at and come from OMM to correct time of journey.

**Comment by danieldunderfelt** [comment]
@haphut mentioned a 30-hour start time. Can this be 24 hours? Everything else, including the HFP data, is 24-hour based.

**Comment by samijuhani** [comment]
Let's talk this with Tomi, but thinking 24 hours will be good in this case.

**Comment by danieldunderfelt** [comment]
@samijuhani currently the time part of the URL is the planned start of the journey, which is used to identify a specific journey. Do we need another timestamp for events that happened in the middle of the journey? If so, we need another segment in the URL for this.

**Comment by danieldunderfelt** [comment]
Can we also change the order of the segments? I suggest date/time/routeId/direction. Then we can progressively add the values to the state as they are written, which means that the url `/journey/20180506/1230` sets the date to 2018-05-06 and the time to 12:30 in the app without setting the route or fetching any hfp data.

**Comment by samijuhani** [comment]
Cannot see reason why not

**Comment by samijuhani** [comment]
Tested to work with OMM version 0.30.0.
