### ISSUE TITLE
Selecting journey from weekly view problem DEV / Vehicle search does not appear

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#500]
Steps:

1. Select journey from weekly arrival vie that does not have arrival time
2. Loads and loads
3. Multiple F5, ctrl+F5
4. No vehicle view

Loads and loads when selecting journey. Selected journey without end time so thought it was the reason but happens with all of those journeys. Seems that after this OR because this vehicle search does not load at all.

![image](https://user-images.githubusercontent.com/39256978/70532041-dc974b80-1b5e-11ea-96c7-ac70c80159e3.png)

After:

![image](https://user-images.githubusercontent.com/39256978/70532934-af4b9d00-1b60-11ea-940c-c749bd7f1874.png)

https://dev.reittiloki.hsl.fi/journey/20191203/153600/1023/1/?date=2019-12-03&stop=1174128&tab=journeys_by_week&mapView=60.19803277939905%2C24.93424415588379&route.routeId=1023&route.direction=1&route.originStopId=1020116&details-tab=journey-events&mapZoom=14&weeklyObservedTimes=arrival&live=false&time=15%3A36%3A00

**Comment by danieldunderfelt** [comment]
Database problem, under investigation.

**Comment by samijuhani** [comment]
Vehicle search is there again and can select journeys from weekly view.
