### ISSUE TITLE
All vehicles are grey in vehicle search in dev with new tables

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#501]
![image](https://user-images.githubusercontent.com/39256978/70615290-ccda3e80-1c14-11ea-9f01-e965a2766715.png)

**Comment by danieldunderfelt** [comment]
The tables are still under construction, this will work when they are ready.

**Comment by danieldunderfelt** [comment]
This is now resolved and does not happen anymore.
