### ISSUE TITLE
Show stops without routes on map

### ISSUE THREAD

**Issue by danieldunderfelt** [HSLdevcom/transitlog-ui#503]
Stops without routes are filtered out since stops are fetched from the DB joined with route segments which have date_begin/date_end validity periods. The app should be able to fetch stops and show them in the stop search and on the map regardless of wether or not they have routes.

**Comment by danieldunderfelt** [comment]
Now testable in dev and stage!

**Comment by samijuhani** [comment]
Can corfim that I can search and see/select in map a stop that is not in use.
