### ISSUE TITLE
Proposed: Show planned routes in map

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#504]
Infra users wants to see all planned routes in the map to see if a place that has construction coming has any routes going there.

**Comment by samijuhani** [comment]
Let's talk this before implementing still

**Comment by danieldunderfelt** [comment]
The JORE export has data for a few months into the future AFAIK. I see no reason to do more than this since Reittiloki is only concerned with historical data. It is simply out of the scope of Reittiloki to include features for future data.

**Comment by samijuhani** [comment]
Planned meant existing routes. Not future.

**Comment by danieldunderfelt** [comment]
Ah right, so a view that shows all routes instead of a single one? That is possible. Sorry, we have discussed scope creep with the team and I conflated that discussion with this issue.

**Comment by samijuhani** [comment]
Not in scope.
