### ISSUE TITLE
Line variants in stop popup confuse user

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#505]
User reported that line variants like "4 7" make one think it means lines 4 and 7. Lets think a better way to display this.

**Comment by danieldunderfelt** [comment]
We could highlight it with a different style and show the complete route name (instead of the line number as it is right now).

**Comment by samijuhani** [comment]
Yeah from - to texts are a good idea. Maybe also make the pop up more compact and with to the screen while we are at it

**Comment by danieldunderfelt** [comment]
I redesigned the route select for stops and grouped them by the first 4 characters of the rotue id. This way route variants are all under one heading. I also added the origin and destination of the route.

![Screenshot from 2020-01-23 06-49-44](https://user-images.githubusercontent.com/3145668/72957575-bc3cec80-3dac-11ea-8b77-ac9578242356.png)

What do you think?

**Comment by danieldunderfelt** [comment]
An example with more variants for a route and more compact route group headings:

![Screenshot from 2020-01-23 07-01-58](https://user-images.githubusercontent.com/3145668/72958002-52254700-3dae-11ea-8b36-6dcce28fe6be.png)

**Comment by danieldunderfelt** [comment]
Updated route buttons for stops are now liveon dev and stage.

**Comment by samijuhani** [comment]
Seems ok
