### ISSUE TITLE
Line 57 missing from stop H4413 -> more robust and monitored Jore import

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#506]
https://reittiloki.hsl.fi/?date=2019-12-17&mapView=60.23613%2C25.08247&route.routeId=&route.direction=0&route.originStopId=&tab=&details-tab=journey-events&mapZoom=15&stop=1471159

It is there in Stage though (and should be)

**Comment by samijuhani** [comment]
And reason is that there is old route active in prod, why?

**Comment by danieldunderfelt** [comment]
Importer seems to be stuck in prod, I'll reboot it!

**Comment by danieldunderfelt** [comment]
The newest import is also faulty, but I managed to get the package from the day before going. Hopefully it will solve the problems. When was the rotue changed? It may take a few days for the database to update.

**Comment by samijuhani** [comment]
Route was changed on Friday 13.12.

**Comment by danieldunderfelt** [comment]
Ok, I'll find out where it is hiding.

**Comment by samijuhani** [comment]
This was fixed now with the fresh data import. For enhancement use this ticket to make monitoring for jore imports and maybe the import itself more robust.

**Comment by danieldunderfelt** [comment]
Line 57 is now fixed after tonight's data import.

**Comment by samijuhani** [comment]
Not really able to test the monitoring, closing.

**Comment by danieldunderfelt** [comment]
It will send error messages and some status messages to the #transitlog-monitoring channel in Slack. In case of an error it mentions me so I'll notice it for sure. Should work well enough!
