### ISSUE TITLE
Events in the wrong order

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#507]
PDE should be after all those

![image](https://user-images.githubusercontent.com/39256978/70992430-5c2e9880-20d2-11ea-990a-6db3c6d2d60a.png)

https://reittiloki.hsl.fi/journey/20191217/104800/1506/1/0030_46?date=2019-12-17&mapView=60.1982354051022%2C24.934372901916507&route.routeId=1506&route.direction=1&route.originStopId=1454140&tab=&details-tab=journey-events&mapZoom=16&stop=1174147&live=false&time=11%3A24%3A40&vehicle=0030%2F46

**Comment by danieldunderfelt** [comment]
This is now fixed, testable in dev and stage!

**Comment by samijuhani** [comment]
Tested ok in stage
