### ISSUE TITLE
Incorrect planned stop time on Pasilan asema

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#508]
Should be 05:13.

![image](https://user-images.githubusercontent.com/39256978/71066777-fe568b00-217b-11ea-860b-acde5a050c47.png)

**Comment by samijuhani** [comment]
https://stage.reittiloki.hsl.fi/journey/20191218/050100/1050/1/0018_801?date=2019-12-18&mapView=60.197510543754696%2C24.93553698062897&stop=1174147&timetableFilters.route.pending=&timetableFilters.route.current=&timetableFilters.minHour.current=&timetableFilters.maxHour.current=&route.routeId=1050&route.direction=1&route.originStopId=1100130&vehicle=0018%2F801&live=false&tab=timetables&details-tab=journey-events&time=05%3A12%3A47&mapZoom=18&timetableFilters.minHour.pending=&timetableFilters.maxHour.pending=

**Comment by samijuhani** [comment]
Also this should be 7:06 instead of 7:07

https://stage.reittiloki.hsl.fi/journey/20191218/064900/1059/1/0018_680?date=2019-12-18&mapView=60.20178034890689%2C24.914866367822672&stop=1174147&timetableFilters.route.pending=&timetableFilters.route.current=&timetableFilters.minHour.current=&timetableFilters.maxHour.current=&route.routeId=1059&route.direction=1&route.originStopId=1100130&vehicle=0018%2F680&live=false&tab=timetables&details-tab=journey-events&time=07%3A15%3A05&mapZoom=13&timetableFilters.minHour.pending=&timetableFilters.maxHour.pending=

**Comment by samijuhani** [comment]
Thinks I found it. It is "calculated" in Jore, suppose Jore import has these wrong times..?

**Comment by danieldunderfelt** [comment]
Yes, the data comes from JORE. As previously stated, I imported the latest working export this morning. I'm not sure how they work, but I assumed it would contain the same data as previous exports starting from since this change was made in JORE. Let's see what the situation is tomorrow, or we have to ask Petri in which export this specific information is.

**Comment by samijuhani** [comment]
Yes I'll report it to Petri if still incorrect tomorrow.

**Comment by danieldunderfelt** [comment]
Still incorrect after tonight's data import.

**Comment by danieldunderfelt** [comment]
Indeed, there are no records in the database for a departure at 05:13 for route 1050 from Pasilan asema. Only 05:12.

**Comment by danieldunderfelt** [comment]
@samijuhani Is this still relevant? Now I'm not seeing any route 50 busses on this stop. Is this a new issue? In that case it would be best to open a new issue.

**Comment by samijuhani** [comment]
Problem was in Jore dump so nothing for us to do. Assigned to myself as a reminder to follow up.
