### ISSUE TITLE
Change time adjustement stop colour to red if early even 1 second

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#509]

**Comment by danieldunderfelt** [comment]
This is now live in stage! I couldn't find an example to test with though.

**Comment by samijuhani** [comment]
Here a test case, works as expected https://stage.reittiloki.hsl.fi/journey/20200106/242000/2235N/2/0018_490?date=2020-01-06&route.routeId=2235N&route.direction=2&route.originStopId=2614260&live=false&tab=&time=24%3A36%3A58&details-tab=journey-events&mapZoom=17&mapView=60.22286110357032%2C24.67759966850281&vehicle=0018%2F490
