### ISSUE TITLE
Stops in wrong order

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#510]
Those stops are from middle of line and missing events. Should not be on top of the list.

https://reittiloki.hsl.fi/journey/20200107/132200/4313/2/0059_6?mapView=60.26740647489434%2C24.835624694824222&date=2020-01-07&route.routeId=4313&route.direction=2&route.originStopId=4120227&tab=&details-tab=journey-events&mapZoom=14&vehicle=0059%2F6&live=false&time=13%3A31%3A49&time_increment=5&mapOverlays=Stopped+vehicle%2CStop+radius&mapBaseLayer=Digitransit

![image](https://user-images.githubusercontent.com/39256978/71895822-c3cc8680-315a-11ea-96bf-c8e6731e2eb7.png)

**Comment by samijuhani** [comment]
Happens also with journeys that are still been driven when looking

**Comment by danieldunderfelt** [comment]
This is now fixed. Due to some edge cases the order of these require many adjustments to get right.

**Comment by samijuhani** [comment]
Happened again in PROD https://reittiloki.hsl.fi/journey/20200120/055800/4614/2/0012_1833?date=2020-01-20&mapView=60.28555599752929%2C24.955830574035648&vehicle=0012%2F1833&route.routeId=4614&route.direction=2&route.originStopId=4400222&live=false&tab=&details-tab=journey-events&mapZoom=15&time=06%3A18%3A44

**Comment by danieldunderfelt** [comment]
This is probably what we tried to prevent with the previous logic. I'll see if I can find the right order.

**Comment by danieldunderfelt** [comment]
The problem is that some events have planned time, and some events have observed time. Putting them in the same list is quite hard, since events with observed time but without planned time may jump ahead or be in the "wrong" position. We could have a separate list for journey events that are not stop events, or is there a lot of value in having them in the same list? @samijuhani

**Comment by samijuhani** [comment]
Routes stops are always in the same order -> stop list always in the same order, not depending at all from the hfp data?

**Comment by danieldunderfelt** [comment]
The previous problem with this list was door events which were out of order, so if we ignore the HFP data those problems will come back. I'll try adjusting the order some more, but there will probably always be cases where some item in the list is in the wrong order.

**Comment by danieldunderfelt** [comment]
@samijuhani A fix is now being deployed to dev and stage!

**Comment by samijuhani** [comment]
Working fine in stage now.
