### ISSUE TITLE
Do not show anything as actual time before last time

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#511]
This confused user. Maybe the easiest is to just show nothing there until actual event has happened. I understand this is a case where at the left bus has arrived to timing stop but not left yet.

![image](https://user-images.githubusercontent.com/39256978/71955128-20c64c00-31f0-11ea-83ef-49f5c749e290.png)

**Comment by danieldunderfelt** [comment]
This is a side-effect of virtual events. I can prevent the virtual events from being used when the time is too close to the planned departure time, but that's about all I can do.

**Comment by danieldunderfelt** [comment]
This is testable in dev and stage!

**Comment by samijuhani** [comment]
A bit time consuming to test. Will try to do it at some point but will trust for now that it works.

**Comment by danieldunderfelt** [comment]
It basically does not color the stops (since virtual events are not created) before the vehicle has visited them. When real stop events appear, they will be used.
