### ISSUE TITLE
Incorrect arrival time in stop view when driven past stop

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#512]
Should not be something after departure.

https://stage.reittiloki.hsl.fi/journey/20200103/154100/2548/2/0022_677?date=2020-01-03&mapView=60.19457723077609%2C24.76595163345337&vehicle=0022%2F677&route.routeId=2548&route.direction=2&route.originStopId=2143201&live=false&tab=&details-tab=journey-events&time=16%3A04%3A53&mapZoom=16&time_increment=1

![image](https://user-images.githubusercontent.com/39256978/71955922-5835f800-31f2-11ea-9f7a-da9bee5d93de.png)

**Comment by samijuhani** [comment]
Also https://reittiloki.hsl.fi/journey/20200102/081500/2542/1/0018_283?date=2020-01-02&route.routeId=2542&route.direction=1&route.originStopId=2412238&live=false&tab=timetables&details-tab=journey-events&time=08%3A36%3A15&mapView=60.17702223809887%2C24.658319950103763&vehicle=0018%2F283&stop=2431251&mapZoom=17&mapOverlays=Stopped+vehicle%2CStop+radius&time_increment=1

**Comment by danieldunderfelt** [comment]
If there is an ARS event it will show up. Should we remove it?

**Comment by samijuhani** [comment]
But how ars is after passage?

**Comment by danieldunderfelt** [comment]
Heh, didn't even notice that! I thought the issue was about not showing arrival times on stops where the vehicle didn't stop.

Anyway, that's how the data is. The ARS event was recorded after the PAS event in this case.

**Comment by samijuhani** [comment]
I'll report the bug to VPC supplier
