### ISSUE TITLE
Design and implement a view/way to show DA and DOUT events

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#515]
At the moment we have no way to show DA (driver sign in) and DOUT (driver sign out) events as those are not done while on a journey.

**Comment by samijuhani** [comment]
First thoughts; new rows to block view that show these events between journeys or new events tab next to block view for these.

**Comment by danieldunderfelt** [comment]
That could work! I see DA and DOUT events in the database so it should be pretty straight-forward.

**Comment by danieldunderfelt** [comment]
This is testable in dev,

**Comment by samijuhani** [comment]
Works as expected.
