### ISSUE TITLE
Wrong timetable times for lines that changed 1.1. 

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#516]
Starting 7.1. for example 1059/2 has incorrect old times shown and therefore data is not possible to be viewed. Problem started 7.1. even though timetables changed already 1.1.

**Comment by danieldunderfelt** [comment]
This is now fixed in production. Stage was working because it has a much smaller amount of JORE data and thus no overlapping departures from this time.
