### ISSUE TITLE
Incorrect departure time in stop timetables view

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#517]
https://reittiloki.hsl.fi/journey/20200104/093300/4574/2/0022_967?date=2020-01-04&route.routeId=4574&route.direction=2&route.originStopId=4150260&tab=timetables&details-tab=journey-events&mapZoom=18&mapView=60.32289230511923%2C25.042321085929874&stop=4700228&vehicle=0022%2F967&live=false&time=10%3A19%3A16&mapOverlays=Stopped+vehicle%2CStop+radius

![image](https://user-images.githubusercontent.com/39256978/72236658-7fb90600-35e0-11ea-9a14-5c7da65e5a1a.png)

**Comment by danieldunderfelt** [comment]
Removed the time for timing stop without a valid event. Testable in stage. The UI cannot yet highlight departures in this list that are lacking observed times, I will fix that next.

**Comment by danieldunderfelt** [comment]
The UI should now highlight selected departures without observed times correctly if I have remembered to push UI changes.

**Comment by samijuhani** [comment]
Empty now in timetables view in stage.

**Comment by samijuhani** [comment]
This is still not fixed in prod, is that right?
