### ISSUE TITLE
FMI API has changed, changes needed to weather feature to work

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#518]
-----Alkuperäinen viesti-----
From: FMI avoin data
Sent: Thursday, November 28, 2019 12:16 PM
To: Markku Huotari
Subject: FMI open data: API-avaimen käyttö loppuu / Use of API key not possible after 2019

Ilmatieteen laitoksen avoimen datan käyttö ei vaadi enää rekisteröitymistä.

Rekisteröityneiden käyttäjien tulee vuoden 2019 loppuun mennessä muuttaa palvelun osoite käyttämään uusia osoitteita. Osoitteet, joissa on Ilmatieteen laitoksen API-avain mukana, eivät toimi enää vuoden 2019 jälkeen.

Vuodesta 2020 alkaen avoin datamme on käytössä ainoastaan ilman API-avainta seuraavien osoitteiden kautta:

https://opendata.fmi.fi/wfs (Latauspalvelu - WFS) https://openwms.fmi.fi/geoserver/wms (Katselupalvelu - WMS)

The use of FMI's open data no longer requires registration.

Registered users should switch over to the new addresses by the end of 2019 in order to use the service. Addresses that include the API key of the Finnish Meteorological Institute will no longer be operational after 2019.

The new addresses are:

https://opendata.fmi.fi/wfs (Download service - WFS) https://openwms.fmi.fi/geoserver/wms (View service - WMS)

**Comment by danieldunderfelt** [comment]
Updated in dev and stage.
