### ISSUE TITLE
Alerts still missing from UI

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#519]
![image](https://user-images.githubusercontent.com/39256978/72415786-ed4e6900-377d-11ea-9b9b-5624d87c4b80.png)

![image](https://user-images.githubusercontent.com/39256978/72415822-022afc80-377e-11ea-93c2-517cfe014d9c.png)

**Comment by samijuhani** [comment]
"Junat: A, P, E ja U. Peruttu. I-junat kääntyvät Kannelmäessä. Syy: Onnettomuus. Arvioitu kesto: 09:26 - 11:00"

**Comment by samijuhani** [comment]
Also "Junat: A, P, U ja E. Palautumassa normaaliksi. "

**Comment by danieldunderfelt** [comment]
Found the issue, fixing.

**Comment by danieldunderfelt** [comment]
This is testable in dev and stage!

**Comment by samijuhani** [comment]
Looks better
