### ISSUE TITLE
Extra departures cause double departure if no vehicle data is found for the extra departure

### ISSUE THREAD

**Issue by danieldunderfelt** [HSLdevcom/transitlog-ui#522]
Departures which have an extra departure which was not driven by a separate vehicle, the departure is double in the route departure list.

Example: https://reittiloki.hsl.fi/journey/20200116/163500/3001Z3/1/0090_6078?date=2020-01-16&route.routeId=3001Z3&route.direction=1&route.originStopId=1020501&tab=journeys&details-tab=journey-events&mapZoom=15&mapView=60.17221405694335%2C24.940917491912845&vehicle=0090%2F6078&live=false&time=16%3A35%3A00&stop=1020501

**Comment by danieldunderfelt** [comment]
Should be fixed, testable in dev and stage!

**Comment by samijuhani** [comment]
Works in stage
