### ISSUE TITLE
Indicate LOC field values in UI

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#523]
This is important new thing from HFP V2 yet to be implemented. Add value of "loc" to all events so user knows if event is triggered manually, odometer, gps, etc.

**Comment by danieldunderfelt** [comment]
This is now testable in dev and stage! Note that for weekly and stop departures, I put the loc data in the tooltip so it is visible on hover. But for other places I created a new loc badge to show it.

**Comment by samijuhani** [comment]
Works as expected in stage.
