### ISSUE TITLE
00:00 starting journey

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#525]
There are nothing drawn in the map to this journey

https://reittiloki.hsl.fi/journey/20200120/240000/1043/2/0012_1208?date=2020-01-20&route.routeId=1043&route.direction=2&route.originStopId=1334191&live=false&tab=&time=24%3A00%3A00&details-tab=journey-events&mapView=60.26195660233018%2C24.88712310791016&mapZoom=12&vehicle=0012%2F1208

Also the same vehicle next journey

https://reittiloki.hsl.fi/journey/20200120/244500/1043/1/0012_1208?date=2020-01-20&route.routeId=1043&route.direction=1&route.originStopId=1020243&live=false&tab=vehicle-journeys&time=24%3A45%3A00&details-tab=journey-events&mapView=60.217136993403884%2C24.91321563720703&mapZoom=12&vehicle=0012%2F1208

But journeys before that are fine.

**Comment by danieldunderfelt** [comment]
This is an edge case where the departure is a "next day departure" but first event of the journey happens on the same real date as the operating date, making the logic that checks if 00 should become 24 fail.

I added the first stop departure event to the time function so it can makde decisions based on more valid information. Testable soon in dev and stage!

**Comment by danieldunderfelt** [comment]
The events should still be saved in our old Timescale cluster, we're investigating why they weren't moved to Citus and attempting to get them over there again.

**Comment by samijuhani** [comment]
Works ok in stage.
