### ISSUE TITLE
Not seeing data from 11.12.2019

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#526]
![image](https://user-images.githubusercontent.com/39256978/72804540-3c523d80-3c59-11ea-8483-e150826d4b05.png)

Looks like there is data but clicking journeys does not work as expected 

https://reittiloki.hsl.fi/journey/20191211/080000/2553/1/0022_1058?date=2019-12-11&mapView=60.249961108326374%2C24.961491838834277&route.routeId=2553&route.direction=1&route.originStopId=4940231&vehicle=0022%2F1058&live=false&tab=&details-tab=journey-events&time=08%3A00%3A00&mapZoom=12

**Comment by danieldunderfelt** [comment]
Well... it looks like the database doesn't contain any vehicle posiitons from this day. Other tables do have data, what's why you're seeing the stop timings and other events.

I'll talk with @AkiValiaho and let's see if we can fix this! I fixed an error that came from the data being empty, but it doesn't change the end result.

**Comment by danieldunderfelt** [comment]
The events should still be saved in our old Timescale cluster, we're investigating why they weren't moved to Citus and attempting to get them over there again.

**Comment by danieldunderfelt** [comment]
The events needed to be partitioned, it is done now.
