### ISSUE TITLE
Differential to arrival time at first stop bug

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#527]
Shouldn't this be 4:12 as in calculated from planned arrival time, not from departure time.

![image](https://user-images.githubusercontent.com/39256978/72985082-dcd96680-3ded-11ea-9815-0a87af506e9c.png)

https://reittiloki.hsl.fi/journey/20200123/070200/1070/2/0012_726?date=2020-01-23&route.routeId=1070&route.direction=2&route.originStopId=1382185&live=false&tab=vehicle-journeys&time=07%3A02%3A00&details-tab=journey-events&mapZoom=12&mapView=60.209463178924935%2C24.971580505371094&vehicle=0012%2F726

**Comment by danieldunderfelt** [comment]
No, the displayed arrival time has had the terminal time subtracted so it's really 7:02. The diff is taken between the observed arrival time (the recorded time of the ARS event) and the planned arrival time which is correct in the image.

The shown planned arrival time with the terminal time subtracted is meant to show the actual time that the vehicle is expected at the first stop. If the diff is more than the terminal time, the vehicle was late and the diff will be colored red.
