### ISSUE TITLE
Seeing data from journey before again in map

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#530]
We fixed this a while ago and no it is back

![image](https://user-images.githubusercontent.com/39256978/73160489-d0a52000-40f1-11ea-97ce-b2d97602f190.png)

https://reittiloki.hsl.fi/journey/20200127/075100/1090/1/0017_28?date=2020-01-27&mapView=60.20839728606549%2C25.14753341674805&route.routeId=1090&route.direction=1&route.originStopId=1531116&tab=&details-tab=journey-events&mapZoom=15&vehicle=0017%2F28&live=false&time=07%3A49%3A59

**Comment by danieldunderfelt** [comment]
It seems that the `is_ongoing` part of the journey events query that we added last time was forgotten during a refactor of the query. Apologies, I'll add it back now.

**Comment by danieldunderfelt** [comment]
Testable in dev and stage now!

**Comment by samijuhani** [comment]
Working in stage as supposed.
