### ISSUE TITLE
Add terminals to map and stop search

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#531]
Terminals include many stops. Add them like in reittiopas = selectin a terminal shows all departures from stops that are part of that terminal. Search also.

![image](https://user-images.githubusercontent.com/39256978/73255010-1fbd8480-41c8-11ea-8930-93a8a7d89595.png)

![image](https://user-images.githubusercontent.com/39256978/73255039-2946ec80-41c8-11ea-8db2-be1d5ebeaf50.png)

![image](https://user-images.githubusercontent.com/39256978/73255147-57c4c780-41c8-11ea-8b01-7688edb74d34.png)

**Comment by danieldunderfelt** [comment]
This is under construction.

**Comment by danieldunderfelt** [comment]
This is now live in dev and stage. It is a larger feature, so comments and feedback is good to have!
