### ISSUE TITLE
Make GPS NOT ok in cases where odometer is used more than couple times

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#545]
Like this, too much odometer used for GPS to be ok status 

https://reittiloki.hsl.fi/journey/20200216/190500/2531B/2/0018_966?date=2020-02-16&route.routeId=2531B&route.direction=2&route.originStopId=2323248&mapOverlays=Stopped+vehicle%2CTerminals&tab=&details-tab=journey-events&mapZoom=14&mapView=60.157397062225606%2C24.738721847534183&vehicle=0018%2F966&live=false&time=19%3A05%3A33

**Comment by danieldunderfelt** [comment]
Should the event health be not ok you mean? It is currently at 92% for that journey, should it just be marked as a fail? Currently the ODO/GPS data isn't looked at for the health score but we can certainly add it.

**Comment by samijuhani** [comment]
Yes this is definitely not ok.

**Comment by danieldunderfelt** [comment]
This is now live on dev!
