### ISSUE TITLE
Slow journeys to appear

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#546]
Why?

Sami  5 minutes ago
Esim tämän lähdön kun avasin eka kertaa niin kesti pitkään. Nyt toki cachesta ei enää https://reittiloki.hsl.fi/journey/20200217/071000/1018/1/0012_1908?date=2020-02-17&route.routeId=1018&route.direction=1&route.originStopId=1060101&live=false&mapOverlays=Stopped+vehicle%2CTerminals&tab=&time=07%3A10%3A00&details-tab=journey-events&mapView=60.18053826658291%2C24.909782409667972&vehicle=0012%2F1908

Sami  3 minutes ago
Tää kesti myös lähelle minuuttia https://reittiloki.hsl.fi/journey/20200131/122500/1064/1/0018_265?date=2020-01-31&mapView=60.17131155205449%2C24.94325637817383&vehicle=0018%2F265&route.routeId=1064&route.direction=1&route.originStopId=1020123&live=false&tab=vehicle-journeys&details-tab=journey-events&time=12%3A26%3A14&mapZoom=13&mapOverlays=Stopped+vehicle%2CStop+radius

**Comment by danieldunderfelt** [comment]
Fix in progress on the database side.
