### ISSUE TITLE
Stops loading in some groups too early

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#548]
Make it so that stops are not loaded like that but like it was before, all stops when we are closer in zoom level.

![image](https://user-images.githubusercontent.com/39256978/74807825-140a3d00-52f2-11ea-9607-7585e87f76c3.png)

**Comment by danieldunderfelt** [comment]
The idea was to show that the stops are turned on in the layer selection, but we can of course go back to how it was before.

It's not a bug since it works exactly as I intended it to work, but we can change it.

**Comment by samijuhani** [comment]
Yeah I see no point to show some stops like this, creates clutter and is of no use.

**Comment by danieldunderfelt** [comment]
The point was to always show stops when they are enabled in the layer menu, giving control to the user. But you are right that it does create clutter so I'll put a zoom limit to it.

**Comment by danieldunderfelt** [comment]
The change is soon in dev!
