### ISSUE TITLE
Missing TLP events

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#549]
Looks like 0017/29 is almost never sending TLP events. Are those in DB? Vehicle pc provider did not found any problems in VPC.

"Liikennevaloetuusilmaisut puuttuvat HFP-sanomista ainakin autosta 0017/29
 
Tammelundin auto 0017/29  Ei TLR-sanomia linjalla 20/1 (yhtä pistettä lukuunottamatta)
 
https://reittiloki.hsl.fi/journey/20200217/072800/1020/1/0017_29?date=2020-02-17&route.routeId=1020&route.direction=1&route.originStopId=1040142&live=false&mapOverlays=Stopped+vehicle%2CTerminals%2CStop+radius&tab=vehicle-journeys&time=07%3A35%3A49&details-tab=journey-events&mapZoom=17&mapView=60.16041342321301%2C24.882177114486698&vehicle=0017%2F29&time_increment=1&stop=1310106&terminal=
 
 
Tammelundin auto 0017/31  TLR-sanomat oikein linjalla 20/1
 
https://reittiloki.hsl.fi/journey/20200217/060100/1020/1/0017_31?date=2020-02-17&route.routeId=1020&route.direction=1&route.originStopId=1040142&live=false&mapOverlays=Stopped+vehicle%2CTerminals%2CStop+radius&tab=vehicle-journeys&time=06%3A11%3A49&details-tab=journey-events&mapZoom=18&mapView=60.16050680882275%2C24.87901210784912&vehicle=0017%2F31&time_increment=1&stop=1310106&terminal=
 
Mistähän moinen ero voi johtua?"

**Comment by danieldunderfelt** [comment]
You are correct, there are only 589 TLA/TLP events in the database for vehicle 0017/29. If I check another vehicle, for example 0012/1403, I get almost 200,000 rows.
