### ISSUE TITLE
Train journey number to train journey details

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#557]
Every train journey has "Junanumero" that is the ID for the journey in VR systems. That is stored in Jore also. Ticket inspector officers asked if they could see it Reittiloki in journey details as they use another system for only to fetch this information.

Example:

 <p:VehicleJourneys><p:ServiceJourney Number="8600"> 

is

3002P/1 4:18.

Could be added next to journey start time or as a new row in route details.

**Comment by danieldunderfelt** [comment]
Pending additional data to JORE export.

**Comment by samijuhani** [comment]
4-number trains fine, still need to check longer number (example from juhannus)

**Comment by samijuhani** [comment]
I can see 5-number train fine https://dev.reittiloki.hsl.fi/journey/20200620/111200/3002U5/1/?date=2020-06-20&route.routeId=3002U5&route.direction=1&route.originStopId=1020502&tab=journeys&details-tab=journey-events&mapZoom=12&mapView=60.180965072947316%2C24.770050048828125&live=false&time=11%3A12%3A00&journeyEventFilters=TIMING_STOP_ARS%2CTERMINAL_ARS%2CDEPARTURE%2CPLANNED&mapOverlays=Stopped+vehicle%2CTerminals
