### ISSUE TITLE
Do not show last stops in terminal view

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#558]
There are also stops that are last stops for routes. Do not show those in terminal view.

![image](https://user-images.githubusercontent.com/39256978/75133026-d33f6900-56e1-11ea-8cdd-752c2023a5bd.png)

**Comment by samijuhani** [comment]
Add this to stop views also!

**Comment by danieldunderfelt** [comment]
Hmm... are you sure? Then there would be no trace of any routes at stops where they end.

**Comment by danieldunderfelt** [comment]
Added, will arrive in dev later today.
