### ISSUE TITLE
Double journey

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#560]
https://reittiloki.hsl.fi/journey/20200305/084300/9643/1/0018_832?date=2020-03-05&mapView=60.17908708345086%2C24.950637817382812&terminal=1000012&stop=&tab=timetables&route.routeId=9643&route.direction=1&route.originStopId=1111117&vehicle=0018%2F832&live=false&details-tab=journey-events&time=08%3A46%3A50&mapZoom=11&journeyEventFilters=TIMING_STOP_ARS%2CTERMINAL_ARS%2CDEPARTURE%2CPLANNED%2C

![image](https://user-images.githubusercontent.com/39256978/75955910-700ebd00-5ebf-11ea-914b-9d25155f4d9d.png)

**Comment by danieldunderfelt** [comment]
Fixed in dev, JORE departure versioning issue. We will probably have to keep adjusting this forever since the data is so untrustworthy.

**Comment by danieldunderfelt** [comment]
This is fixed and in production.
