### ISSUE TITLE
Hakaniemi station missing 502 pde always even though it is there in list

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#574]
https://reittiloki.hsl.fi/journey/20200331/062400/2502/1/0022_980?date=2020-03-31&mapView=60.178217444586835%2C24.95304644107819&mapZoom=18&live=false&time=06%3A25%3A59&terminal=1000012&stop=&tab=timetables&route.routeId=2502&route.direction=1&route.originStopId=1100101&vehicle=0022%2F980&mapOverlays=Stopped+vehicle%2CTerminals%2CStops&details-tab=journey-events&journeyEventFilters=ALL%2CTIMING_STOP_ARS%2CTERMINAL_ARS%2CDEPARTURE%2CVJA%2CARS%2CDOO%2CDOC%2CPDE%2CDEP%2CDUE%2CARR%2CTLR%2CTLA%2CPAS%2CVJOUT%2CPLANNED&timetableFilters.route.pending=502&timetableFilters.route.current=502&timetableFilters.minHour.current=&timetableFilters.maxHour.current=

![image](https://user-images.githubusercontent.com/39256978/78014264-5b9fd200-7350-11ea-9e3c-b7fb55132af0.png)

**Comment by danieldunderfelt** [comment]
It looks like the route stops at a stop which is not part of the terminal. That the terminal includes departures for the route seems like a JORE validity issue again.

**Comment by danieldunderfelt** [comment]
This is fixed.

![Screenshot from 2020-06-26 07-48-12](https://user-images.githubusercontent.com/3145668/85821501-746a2900-b781-11ea-9673-6e189bd6d7d3.png)

**Comment by samijuhani** [comment]
Yep asked if it should be added to terminal and seems so now.
