### ISSUE TITLE
Case special day timetables that have been removed since

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#583]
Vappu timetables were in Jore but were removed afterwards due corona. We do not have a way to react to this at the moment (other than delete manually). Make up a process to make this work.

Couple ideas:

1. We'll not import future data until day/two before as this is a history app and it is not needed anyway
2. Use straight Jore database connection

**Comment by danieldunderfelt** [comment]
Not importing future data is a great idea, but we need a way to determine if the data is actually in the future. For example, the rows that caused the problem today were imported in march, with a validity period spanning february to june. So from the importer's point of view, the rows would not be future rows and would not have been excluded by a future data -filter.

Maybe Petri Selkisalo could help?
