### ISSUE TITLE
Missing canceled journeys after 00:00

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#584]
All happened after midnight. 
04.05.2020 02:07:16 | Lähtö peruttu | 67/2 00:45 | 04.05.2020 00:45 - 04.05.2020 01:15 | Ajoneuvorikko / Moottorin häiriö | P
-- | -- | -- | -- | -- | --
04.05.2020 01:52:10 | Lähtö peruttu | 65/1 01:24 | 04.05.2020 01:24 - 04.05.2020 01:45 | Ajoneuvorikko / Moottorin häiriö | P

P 3.5.2020 22:48 -
Juna P Helsinki - Aviapolis - Helsinki via Myyrmäki kello 00:48 on peruttu.

**Comment by danieldunderfelt** [comment]
These don't seem to exist in the database.

![Screenshot from 2020-05-04 13-07-51](https://user-images.githubusercontent.com/3145668/80955693-57ac1780-8e08-11ea-8f12-5dc6bba6294f.png)

**Comment by samijuhani** [comment]
Separated trains to #585 this is for after 00:00 cancelled journeys strictly
