### ISSUE TITLE
225 14.5.-27.5. timetables

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#588]
There are normal timetables but should be korona-ones. Check also other mentioned routes

https://www.hsl.fi/liikennetiedotteet/2020/koulujen-lahiopetukseen-palaamisen-liittyvat-muutokset-busseilla-14-295

**Comment by danieldunderfelt** [comment]
JORE import rerun, should work now in large parts.

**Comment by danieldunderfelt** [comment]
I thiink this could be fixed by ordering a new export from Petri for these dates. I'll ask him.

**Comment by danieldunderfelt** [comment]
New export requested.
