### ISSUE TITLE
Change arrival to timing stop colour to green

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#589]

**Comment by samijuhani** [comment]
This has still red arrival https://dev.reittiloki.hsl.fi/journey/20200624/055000/1023/2/0012_1614?date=2020-06-24&mapView=60.19531060556565%2C24.928429126739506&mapZoom=15&stop=1173148&terminal=&tab=timetables&route.routeId=1023&route.direction=2&route.originStopId=1160113&vehicle=0012%2F1614&live=false&details-tab=journey-events&mapOverlays=Stopped+vehicle%2CTerminals&time=06%3A00%3A37&journeyEventFilters=TIMING_STOP_ARS%2CPLANNED

![image](https://user-images.githubusercontent.com/39256978/85549291-82f0fd00-b628-11ea-82b2-c641635deb14.png)

**Comment by danieldunderfelt** [comment]
Probably just an instance of the UI that was slow to update. Sometimes they can be very slow. Works today!

**Comment by samijuhani** [comment]
Yep!
