### ISSUE TITLE
Timing stop pde colour change

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#592]
Waiting for business decision of exact spec

**Comment by samijuhani** [comment]
Time limit shall be 5secs instead of 10sec that it is now.

**Comment by danieldunderfelt** [comment]
Currently the early threshold is 0. It should be -5?

**Comment by danieldunderfelt** [comment]
![Screenshot from 2020-06-25 12-54-44](https://user-images.githubusercontent.com/3145668/85698193-1be44e80-b6e3-11ea-8fce-7dbdbefc51fc.png)

Is this now OK? Pushing this to dev now.

**Comment by danieldunderfelt** [comment]
(Destination stop type is currently not used but it's there for the future if needed)
