### ISSUE TITLE
345 missing journeys 

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#593]
![image](https://user-images.githubusercontent.com/39256978/85552355-9782c480-b62b-11ea-8498-6f104dc9d308.png)

**Comment by samijuhani** [comment]
Got feedback also from 38. Assume this is broader, need fix asap. I see that Jore-import has went through in 2 days, must be that?

**Comment by danieldunderfelt** [comment]
JORE import rerun, should work now in large parts.
