### ISSUE TITLE
Should data of journeys in block view be viewable even though we do not have that journey in db from Jore

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#594]
We cases we have been missing journeys from Jore but there is data from vehicles seeable in block view. Clicking that does not work. Should we enable this back up so that it would open the data as it is there for sure in citus?

Example: https://reittiloki.hsl.fi/journey/20200624/062600/2345/2/0022_1072?date=2020-06-24&mapOverlays=Stopped+vehicle%2CTerminals&mapView=60.26417151281828%2C24.79820251464844&route.routeId=2345&route.direction=2&route.originStopId=2724255&tab=vehicle-journeys&details-tab=route-stops&mapZoom=11&vehicle=0022%2F1072&live=false&time=06%3A26%3A00

**Comment by MinnaEmilia** [comment]
Tälle ominaisuudelle ei ole tarvetta Reittilokissa. -> suljetaan tiketti.
