### ISSUE TITLE
Incorrect colour in stop departure view

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#600]
This should be red as it is early departured from first stop of journey 

https://reittiloki.hsl.fi/journey/20200702/121700/6171/1/0018_223?date=2020-07-02&mapView=60.160060692113895%2C24.736876487731937&mapZoom=17&stop=2314219&terminal=&tab=timetables&route.routeId=6171&route.direction=1&route.originStopId=2314219&vehicle=0018%2F223&live=false&details-tab=journey-events&time=12%3A15%3A02&journeyEventFilters=ALL%2CTIMING_STOP_ARS%2CTERMINAL_ARS%2CDEPARTURE%2CARR%2CDUE%2CVJA%2CARS%2CDOO%2CPDE%2CDEP%2CDOC%2CWAIT%2CPAS%2CVJOUT%2CPLANNED&mapOverlays=Stopped+vehicle%2CTerminals%2CStop+radius

![image](https://user-images.githubusercontent.com/39256978/86438736-d392e500-bd0f-11ea-9d75-52b6752149ad.png)

**Comment by samijuhani** [comment]
Shouldn't journey "01:57" be "-01:57" too?

**Comment by danieldunderfelt** [comment]
On hold until the data is found in the database again.

**Comment by SuviRossi** [comment]
@danieldunderfelt I found this rather old ticket but there is similar case now. The colour codes are incorrect as those that should be red - are yellow. 
![#600](https://user-images.githubusercontent.com/74956804/111298806-de03cd80-8657-11eb-9e41-4c25c4079fe3.jpg)
