### ISSUE TITLE
Vehicles which have doors always open should be shown as unhealthy data

### ISSUE THREAD

**Issue by mjaakko** [HSLdevcom/transitlog-ui#601]
e.g. 
![image](https://user-images.githubusercontent.com/32361480/86911170-85248280-c123-11ea-982b-3459e258b9f5.png)

**Comment by danieldunderfelt** [comment]
What is this based on? Currently the doors pass the test if DOO or DOC events are found, or if stop events where the door is open are found. The assumption is that if the information about doors opening are found, then the doors work. Are there cases where the doors are wrongly reported as open?

**Comment by samijuhani** [comment]
Incorrectly installed systems in bus. Could be this always open (we know it must be an error) or inverted (open when closed) that is not relevant here.

**Comment by MinnaEmilia** [comment]
Logic in Reittiloki side works as it should.  --> closing ticket from this board.
