### ISSUE TITLE
Add passenger counting stats

### ISSUE THREAD

**Issue by samijuhani** [HSLdevcom/transitlog-ui#604]
At the moment Suomenlinna ferry has passenger counting simply in occu value of vp messages. Add those to Reittiloki (database if not yet there and UI). Later on there will be real time passenger counting with own hfp event messages (apc) but let's make a ne issue for that.

/hfp/v2/journey/ongoing/vp/ferry/0060/00004/1019/2/Kauppatori/09:40/1030701/3/60;24/19/58/71 {"VP":{"desi":"19","dir":"2","oper":60,"veh":4,"tst":"2020-08-06T06:45:17.033Z","tsi":1596696317,"spd":3.9611880000000004,"hdg":342,"lat":60.157317,"acc":null,"dl":null,"odo":null,"drst":null,"oday":"2020-08-06","start":"09:40","loc":"GPS","route":"1019",**"occu":4,**"label":"SUOKKI","long":24.981333}}

**Comment by samijuhani** [comment]
As this is in VP messages, I'd think design-wise most logical could be to add it as a new row here.
![image](https://user-images.githubusercontent.com/39256978/89500355-489f8180-d7ca-11ea-9b32-f665a3175d8d.png)

As it is a changing value in all other transport modes than ferry, maybe not sense to add it to trip details at this moment...

**Comment by mjaakko** [comment]
How should we handle special cases 0 and 100?

**Comment by samijuhani** [comment]
Should we expect these in Reittiloki only for ferry's for now. I thinks hfp itself needs to have a solution for that -> new issue in Transitdata?

**Comment by danieldunderfelt** [comment]
Why are those special?

**Comment by samijuhani** [comment]
Special as in if ther is no real time passenger counting available (like in all other thatn ferry at the moment), amounts are always 0 or 100 and you can not say if the those amounts are real time or not from the data itself. 0 could be no_data or empty.

**Comment by MinnaEmilia** [comment]
Need has been changed. This ticket will be closed and new needs described in new tickets.
