### ISSUE TITLE
Investigate how to keep manually loaded HFP events for more than 4 months (1-2d)

### ISSUE THREAD

**Issue by danieldunderfelt** [HSLdevcom/transitlog-ui#624]
It is possible to load HFP events from any date with https://github.com/HSLdevcom/hfp-loader, but the database removes data that is older than 4 months by dropping partitions.

In order to enable loading dates older than four months and keep them in the database for a while, a solution to this needs to be found.

Ideas:

- Create a separate app that cleans up old events. Manually loaded events can add some sort of value to prevent them from being cleaned up.
- Use another column than tst for partitioning. This column value can be tst by default, but the manually added rows can set a value into the future. All clients of the database would continue to use the tst value as before.

**Comment by mjaakko** [comment]
What's the typical use case for this? If the amount of data is small (e.g. few days), it could be possible to use a different table for manually loaded data.

**Comment by mjaakko** [comment]
Currently in dev there is a partitioned table for manually loaded HFP data that stores data for one week after it has been loaded. There is also a SQL view `vehicleposition_all` that can be used to query from both tables. Let's wait for more input on the use case before changing SQL queries.

**Comment by teemu8655** [comment]
Muutoksella on suorituskykyvaikutuksia. Toteutus riippuu paljon käyttötarkoituksesta.
