### ISSUE TITLE
APC data to db

### ISSUE THREAD

**Issue by ahjyrkia** [HSLdevcom/transitlog-ui#721]
Tällä hetkellä reittilokin tietokannasta ei löydy matkustajalaskentaan liittyvää APC-dataa. Dataputki on jo olemassa transitdatan puolella. 

- Lisätään datan käsittely joko hfp-split-sinkkiin tai tehdään oma sinkki matkustajatiedoille.
- Partitiointi?

**Comment by mjaakko** [comment]
APC data is now available in Transitlog dev DB

**Comment by mjaakko** [comment]
TODO: handle cases where timestamp is incorrect (if there is no partition in the DB for the timestamp, insertion will fail)

**Comment by mjaakko** [comment]
Done
