### ISSUE TITLE
UI looks broken on mobile browser

### ISSUE THREAD

**Issue by tuukka** [HSLdevcom/transitlog-ui#79]

**Comment by danieldunderfelt** [comment]
AFAIK this application is only meant for desktop use. Since there are so many filters and other UI elements, a mobile version would look quite different and need separate planning and design.

**Comment by tuukka** [comment]
The solution could perhaps be an error message like "Your screen is too small for this tool, please switch to a computer."

**Comment by danieldunderfelt** [comment]
That's a good solution! We're still in the thick of development at the moment and haven't yet given a thought to other platforms than desktop.

**Comment by danieldunderfelt** [comment]
The app will probably not be mobile friendly in the foreseeable future.
